// Post-campaign challenges preserve the ordinary game's permanent stats.
const RunProfiles={normal:{name:'普通旅程',desc:'完整分支战役与自由构筑',hp:1,damage:1,speed:1},nightmare:{name:'噩梦远征',desc:'敌人生命 +35% · 伤害 +20% · 速度 +5%',hp:1.35,damage:1.2,speed:1.05},iron:{name:'铁誓挑战',desc:'最多三件武器 · 禁止治疗 · 保留闪避与技能',hp:1,damage:1,speed:1}};
const RunAchievements={first:'旅途终章',nightmare:'噩梦旅者',iron:'铁誓守约',warden:'守卫凯旋',ranger:'游侠凯旋',arcanist:'术士凯旋',orbit:'环刃大师',projectile:'远射大师',summon:'契约大师'};
(() => {
  const old={};for(const k of ['startNewGame','loadLevel','loadAndContinue','saveProgress','loadMeta','finishCampaignStage','getMenuLayout','updateMenu','renderMenu','renderHUD','update','selectUpgrade','selectChestReward','upgradePrerequisiteMet','createRecoveryChoice','updateMeta'])old[k]=Game[k];
  const enemyUpdate=Enemy.prototype.update,enemyTake=Enemy.prototype.takeDamage,heal=Player.prototype.heal;
  const finite=(v,lo,hi,fallback=lo)=>Number.isFinite(v)?clamp(v,lo,hi):fallback;
  Object.assign(Game,{
    selectedRunProfile:'normal',runProfile:'normal',
    selectRunProfile(id){if(!RunProfiles[id]||(id!=='normal'&&!(this.meta.campaignClears>0)))return false;this.selectedRunProfile=id;return true;},
    applyRunProfile(e,restoring=false){if(e._runProfileApplied)return;const d=RunProfiles[this.runProfile]||RunProfiles.normal;const hp=e.hp;e.maxHp*=d.hp;e.hp=restoring?Math.min(hp,e.maxHp):hp*d.hp;e.damage*=d.damage;e.speed*=d.speed;e._runProfileApplied=true;},
    enforceChallenge(){if(this.runProfile==='iron'&&this.player){this.player.weaponCapacity=3;if(this.player.weapons.length>3)this.player.weapons.length=3;}},
    startNewGame(...a){if(this.state==='gameover')this.selectedRunProfile=this.runProfile;this.runProfile=RunProfiles[this.selectedRunProfile]&& (this.selectedRunProfile==='normal'||this.meta.campaignClears>0)?this.selectedRunProfile:'normal';this.challengeAwarded=false;this._challengeStarting=true;try{const r=old.startNewGame.apply(this,a);this.enforceChallenge();return r;}finally{this._challengeStarting=false;}},
    loadLevel(...a){const hp=this.player?.hp,r=old.loadLevel.apply(this,a);if(this.runProfile==='iron'&&!this._challengeStarting&&Number.isFinite(hp))this.player.hp=Math.min(hp,this.player.getMaxHp());this.enforceChallenge();return r;},
    upgradePrerequisiteMet(u){if(this.runProfile==='iron'&&['regen','lifesteal'].includes(u?.id))return false;return old.upgradePrerequisiteMet.call(this,u);},
    createRecoveryChoice(){if(this.runProfile!=='iron')return old.createRecoveryChoice.call(this);return {id:'iron_range',name:'铁誓磨砺',desc:'武器范围 +3%',icon:'weapons/sword',rarity:'common',isFallback:true,apply:p=>p.stats.rangeMult*=1.03};},
    selectUpgrade(...a){const r=old.selectUpgrade.apply(this,a);this.enforceChallenge();return r;},
    selectChestReward(...a){const r=old.selectChestReward.apply(this,a);this.enforceChallenge();return r;},
    loadMeta(){old.loadMeta.call(this);let d;try{d=JSON.parse(localStorage.getItem(this.metaKey)||'null');}catch{}this.meta.campaignClears=Math.floor(finite(d?.campaignClears,0,100000));this.meta.achievements=Array.isArray(d?.achievements)?[...new Set(d.achievements.filter(id=>RunAchievements[id]))]:[];this.meta.challengeRecords=d?.challengeRecords&&typeof d.challengeRecords==='object'?d.challengeRecords:{};},
    awardCampaignClear(route){
      if(this.bossDefeated&&!this.challengeAwarded&&route?.length===3&&this.levelData.theme===route[2]&&this.runHistory?.length===2&&this.runHistory.every((r,i)=>r.completed&&r.theme===route[i]&&Number.isFinite(r.seconds))){
        this.challengeAwarded=true;this.meta.campaignClears=(this.meta.campaignClears||0)+1;const badges=new Set(this.meta.achievements||[]);badges.add('first');badges.add(this.player.characterId);if(this.runProfile!=='normal')badges.add(this.runProfile);
        for(const type of ['orbit','projectile','summon'])if(this.player.weapons.some(w=>(type==='projectile'?['ranged','projectile','homing'].includes(w.def.type):w.def.type===type)&&w.level>=(CONFIG.WEAPON_MAX_LEVEL||6)))badges.add(type);
        this.meta.achievements=[...badges].filter(id=>RunAchievements[id]);const key=this.runProfile+':'+this.player.characterId+':'+route.join('-'),seconds=this.getRunSummary().seconds;
        this.meta.challengeRecords=this.meta.challengeRecords||{};const prior=this.meta.challengeRecords[key];this.meta.challengeRecords[key]={clears:(prior?.clears||0)+1,bestSeconds:Math.min(prior?.bestSeconds||Infinity,seconds)};this.saveMeta();this.addMessage('挑战与成就已记录','#ddc27d');
      }
    },
    updateMeta(){const before=!!this.challengeAwarded;if(this.state==='victory'&&!this.campaignMode&&this.levelData?.theme==='hell')this.awardCampaignClear(['village','mine','hell']);const r=old.updateMeta.call(this);if(!before&&this.challengeAwarded)this.saveProgress();return r;},
    finishCampaignStage(){if(this.campaignMode&&!this.getCampaignRouteOptions().length)this.awardCampaignClear(this.campaignRoute);return old.finishCampaignStage.call(this);},
    serializeBoss(){const b=this.enemies.find(e=>e.alive&&e.isBoss);if(!b)return null;this.applyRunProfile(b);return {type:b.type,x:b.x,y:b.y,hp:b.hp,phase:b.phase,enraged:b.enraged,signatureIndex:b.signatureIndex||0};},
    saveProgress(){old.saveProgress.call(this);if(!this.player?.alive)return;try{const d=JSON.parse(localStorage.getItem(this.saveKey));if(!d)return;d.runProfile=this.runProfile;d.challengeAwarded=!!this.challengeAwarded;d.bossSnapshot=this.serializeBoss();localStorage.setItem(this.saveKey,JSON.stringify(d));}catch{}},
    loadAndContinue(){let d;try{d=JSON.parse(localStorage.getItem(this.saveKey)||'null');}catch{}this.runProfile=RunProfiles[d?.runProfile]?d.runProfile:'normal';this.selectedRunProfile=this.runProfile;this.challengeAwarded=!!d?.challengeAwarded;old.loadAndContinue.call(this);this.enforceChallenge();for(const e of this.enemies)this.applyRunProfile(e,true);
      const b=this.enemies.find(e=>e.alive&&e.isBoss),s=d?.bossSnapshot;if(b&&s?.type===b.type){b.x=finite(s.x,50,this.levelData.mapW*48-50,b.x);b.y=finite(s.y,50,this.levelData.mapH*48-50,b.y);b.hp=finite(s.hp,1,b.maxHp,b.maxHp);b.enraged=!!s.enraged;b.phase=b.enraged?2:1;if(b.enraged){b.speed*=1.25;b.damage*=1.15;}b.signatureIndex=Math.floor(finite(s.signatureIndex,0,100000));b.bossState='recover';b.stateTimer=1.1;b.abilityTimer=1.1;b.signatureEffects=[];this.resolvePropCollision(b);}
      if(this.campaignFinished&&!this.challengeAwarded){this.finishCampaignStage();this.saveProgress();}
    },
    getMenuLayout(){const l=old.getMenuLayout.call(this);l.challenge={x:l.start.x,y:l.visible.y+312*l.scale,w:l.start.w,h:30*l.scale};return l;},
    getChallengeLayout(){const v=this.getVisibleCanvasRect(),w=Math.min(580,v.w-28),x=v.x+(v.w-w)/2;return {v,cards:Object.keys(RunProfiles).map((id,i)=>({id,x,y:v.y+90+i*76,w,h:65})),back:{x,y:v.y+v.h-48,w,h:34}};},
    updateMenu(){if(this._settingsOverlay)return old.updateMenu.call(this);if(this._challengeMenu){const l=this.getChallengeLayout();for(const r of l.cards)if(Input.consumeClick(r.x,r.y,r.w,r.h)){if(this.selectRunProfile(r.id)){this._challengeMenu=false;Audio2.click();}else this.addMessage('完成三段战役后解锁','#c9ac72');return;}const r=l.back;if(Input.wasPressed('Escape')||Input.consumeClick(r.x,r.y,r.w,r.h))this._challengeMenu=false;return;}const r=this.getMenuLayout().challenge;if(Input.consumeClick(r.x,r.y,r.w,r.h)){this._challengeMenu=true;Audio2.click();return;}return old.updateMenu.call(this);},
    renderMenu(){old.renderMenu.call(this);const c=this.ctx,l=this.getMenuLayout(),r=l.challenge;c.fillStyle='#101917';c.fillRect(r.x-2,r.y-3,r.w+4,r.h+6);this.drawButton(r.x,r.y,r.w,r.h,'难度与成就 · '+RunProfiles[this.selectedRunProfile].name,'#b5c9ae');if(!this._challengeMenu)return;const q=this.getChallengeLayout(),v=q.v;c.save();c.fillStyle='#101917';c.fillRect(0,0,960,540);c.textAlign='center';c.fillStyle='#dfbf72';c.font='bold 23px Courier New';c.fillText('远征挑战',v.x+v.w/2,v.y+44);c.font='11px Courier New';c.fillStyle='#a0b1aa';c.fillText('完成三段战役解锁噩梦与铁誓',v.x+v.w/2,v.y+68);
      for(const b of q.cards){const d=RunProfiles[b.id],locked=b.id!=='normal'&&!(this.meta.campaignClears>0);this.drawButton(b.x,b.y,b.w,b.h,'',locked?'#777f76':'#dbbd81');c.textAlign='center';c.font='bold 15px Courier New';c.fillStyle=locked?'#777f76':'#dbbd81';c.fillText((locked?'锁定 · ':'')+d.name,b.x+b.w/2,b.y+23);c.font='10px Courier New';c.fillStyle='#a5b6a8';this.drawTextBlock(c,d.desc,b.x+b.w/2,b.y+43,b.w-18,12,2);}
      const earned=this.meta.achievements||[];c.font='11px Courier New';c.textAlign='center';c.fillStyle='#b9cbb1';c.fillText(`战役完成 ${this.meta.campaignClears||0} 次 · 成就 ${earned.length}/${Object.keys(RunAchievements).length}`,v.x+v.w/2,v.y+346);this.drawTextBlock(c,earned.map(id=>RunAchievements[id]).join(' · ')||'首次通关、角色凯旋与满级构筑可获得成就',v.x+v.w/2,v.y+370,v.w-32,18,4);this.drawButton(q.back.x,q.back.y,q.back.w,q.back.h,'返回选择旅者','#b5c9ae');c.restore();},
    renderHUD(){old.renderHUD.call(this);if(this.runProfile==='normal')return;const v=this.getVisibleCanvasRect(),c=this.ctx;c.save();c.textAlign='right';c.fillStyle='#e6c38e';c.font='11px Courier New';c.fillText(RunProfiles[this.runProfile].name,v.x+v.w-18,v.y+96);c.restore();},
    trimCombatVisuals(){for(const [key,pool,max] of [['particles',this.particlePool,600],['damageNumbers',this.damageNumberPool,160]])if(this[key]?.length>max){for(const item of this[key].splice(0,this[key].length-max))pool.release(item);}},
    update(dt){if(this.state==='playing'){this.enforceChallenge();for(const e of this.enemies)this.applyRunProfile(e);}const r=old.update.call(this,dt);this.trimCombatVisuals();return r;}
  });
  Enemy.prototype.update=function(...a){Game.applyRunProfile(this);return enemyUpdate.apply(this,a);};
  Enemy.prototype.takeDamage=function(...a){Game.applyRunProfile(this);return enemyTake.apply(this,a);};
  Player.prototype.heal=function(amount){if(Game.runProfile==='iron')return;return heal.call(this,amount);};
})();
