// Endings require a completed route and its actual oath choices.
(() => {
 const old={};for(const k of ['startNewGame','finishCampaignStage','saveProgress','loadAndContinue','loadMeta','resetSave','getEndingText','update','render'])old[k]=Game[k];
 let serial=0;const runId=()=>Date.now()+':'+(++serial);
 const definitions={purify:{name:'净化誓印',desc:'腐化已归零。舍弃当前首领能力，将旅途中的誓印归还净潮。'},use:{name:'利用誓印',desc:'保留当前首领能力，带着它的代价离开。旅者成为新一任誓印持有者。'}};
 Object.assign(Game,{
  journeyEnding:null,journeyEndingPending:false,journeyEndingRunId:'',
  startNewGame(...a){this.journeyEnding=null;this.journeyEndingPending=false;this.journeyEndingRunId=runId();return old.startNewGame.apply(this,a);},
  journeyEndingSource(){return 'ending:'+this.journeyEndingRunId+':'+this.runSeed+':'+this.campaignRoute.join('-');},
  hasLegalEndingJourney(){const route=this.campaignRoute;if(!this.campaignMode||this.campaignVersion!==2||route.length!==4||!this.bossDefeated||this.levelData.theme!==route.at(-1)||!this.runHistoryComplete||this.runHistory.length!==3||this.runHistory.some((r,i)=>!r.completed||r.theme!==route[i])||!this.isValidCampaignRoute(route,CONFIG.CAMPAIGN_TIERS,{campaignVersion:2,journeyConsequences:this.journeyConsequences}))return false;return route.every((theme,i)=>this.bossOath.decisions.filter(d=>d.theme===theme&&d.source===`${theme}:${i+1}:0:${this.runSeed}`&&['accept','replace','decline'].includes(d.choice)).length===1);},
  getJourneyEndingEntries(){if(!this.hasLegalEndingJourney())return [];const c=this.journeyConsequences,decisions=this.bossOath.decisions,entries=[];if(c.corruption===0&&decisions.some(d=>d.choice==='decline'))entries.push({id:'purify',...definitions.purify});if(this.bossOath.owned&&decisions.some(d=>['accept','replace'].includes(d.choice)))entries.push({id:'use',...definitions.use});return entries;},
  finishCampaignStage(){if(!this.journeyEnding&&!this.getCampaignRouteOptions().length&&this.hasLegalEndingJourney()){this.journeyEndingPending=true;this.state='journeyEndingChoice';this.saveProgress();return;}return old.finishCampaignStage.call(this);},
  makeJourneyEnding(id){const hidden=!!this.journeyConsequences.shortcutUsed&&this.campaignRoute[1]==='marsh';return {id,source:this.journeyEndingSource(),hidden,title:id==='purify'?(hidden?'沉誓归潮':'破誓归途'):(hidden?'深渊承誓':'持刃新王')};},
  applyJourneyEnding(ending){this.journeyEnding=ending;this.journeyEndingPending=false;if(ending.id==='purify'){this.bossOath.owned='';this.bossOath.fields=[];this.bossOath.cooldown=0;this.journeyConsequences.corruption=0;}return old.finishCampaignStage.call(this);},
  chooseJourneyEnding(id){if(this.state!=='journeyEndingChoice'||!this.journeyEndingPending||!this.player?.alive||!this.getJourneyEndingEntries().some(e=>e.id===id))return false;const ending=this.makeJourneyEnding(id),bank=this.meta.journeyEndings||{purify:0,use:0,records:{}},record=bank.records?.[ending.source];if(record){this.applyJourneyEnding({...ending,id:record.id,title:record.title,hidden:record.hidden});this.saveProgress();return false;}
   const next={...bank,[id]:(bank[id]||0)+1,records:{...bank.records,[ending.source]:ending}};try{localStorage.setItem(this.metaKey,JSON.stringify({...this.meta,journeyEndings:next,settings:this.settings}));}catch{this.addMessage('结局记录保存失败 · 请稍后重试','#d6ac8a');return false;}this.meta.journeyEndings=next;this.applyJourneyEnding(ending);this.saveProgress();return true;
  },
  saveProgress(){old.saveProgress.call(this);if(!this.player?.alive)return;try{const d=JSON.parse(localStorage.getItem(this.saveKey)||'null');if(d){d.journeyEnding=this.journeyEnding;d.journeyEndingPending=!!this.journeyEndingPending;d.journeyEndingRunId=this.journeyEndingRunId;localStorage.setItem(this.saveKey,JSON.stringify(d));}}catch{}},
  loadAndContinue(){let d;try{d=JSON.parse(localStorage.getItem(this.saveKey)||'null');}catch{}this.journeyEnding=null;this.journeyEndingPending=false;this.journeyEndingRunId=typeof d?.journeyEndingRunId==='string'&&d.journeyEndingRunId?d.journeyEndingRunId:runId();const r=old.loadAndContinue.call(this);if(!this.hasLegalEndingJourney()){if(d&&!d.journeyEndingRunId)this.saveProgress();return r;}const stored=d?.journeyEnding,record=this.meta.journeyEndings?.records?.[this.journeyEndingSource()];if(record&&definitions[record.id]){this.journeyEnding={...record};if(!this.campaignFinished)this.applyJourneyEnding(this.journeyEnding);else this.state='victory';}else if(stored&&definitions[stored.id]&&stored.source===this.journeyEndingSource()){this.journeyEnding={...stored};this.state='victory';}else if(d?.journeyEndingPending){this.journeyEndingPending=true;this.state='journeyEndingChoice';}if(d&&!d.journeyEndingRunId)this.saveProgress();return r;},
  loadMeta(){old.loadMeta.call(this);let d;try{d=JSON.parse(localStorage.getItem(this.metaKey)||'null');}catch{}const m=d?.journeyEndings;this.meta.journeyEndings={purify:Number.isFinite(m?.purify)?Math.max(0,Math.floor(m.purify)):0,use:Number.isFinite(m?.use)?Math.max(0,Math.floor(m.use)):0,records:{}};for(const [source,e] of Object.entries(m?.records||{}))if(source.startsWith('ending:')&&definitions[e?.id])this.meta.journeyEndings.records[source]={id:e.id,source,hidden:!!e.hidden,title:typeof e.title==='string'?e.title:definitions[e.id].name};},
  resetSave(){old.resetSave.call(this);this.journeyEnding=null;this.journeyEndingPending=false;this.meta.journeyEndings={purify:0,use:0,records:{}};},
  getEndingText(){const e=this.journeyEnding;if(!e)return old.getEndingText.call(this);const boss=CONFIG.ENEMIES[this.levelData.bossId]?.name||'最终首领';return boss+'已被击败。'+e.title+' · '+(e.id==='purify'?'誓印归于净潮，旅者舍弃借来的力量。':'旅者留下首领的力量，也承担它的代价。')+(e.hidden?' 沉没捷径的誓灯记住了你的选择。':'');},
  getJourneyEndingLayout(){const v=this.getVisibleCanvasRect(),w=Math.min(580,v.w-28),x=v.x+(v.w-w)/2,entries=this.getJourneyEndingEntries(),h=Math.min(120,(v.h-178)/Math.max(2,entries.length)-12);return {v,cards:entries.map((e,i)=>({...e,x,y:v.y+124+i*(h+12),w,h}))};},
  update(dt){if(this.state!=='journeyEndingChoice')return old.update.call(this,dt);const l=this.getJourneyEndingLayout();for(const [i,r] of l.cards.entries())if(Input.wasPressed('Digit'+(i+1))||Input.consumeClick(r.x,r.y,r.w,r.h)){this.chooseJourneyEnding(r.id);return;}},
  render(){old.render.call(this);if(this.state!=='journeyEndingChoice')return;const c=this.ctx,l=this.getJourneyEndingLayout(),v=l.v;c.save();c.fillStyle='#101b17';c.fillRect(0,0,960,540);c.textAlign='center';c.font='bold 23px Courier New';c.fillStyle='#dfc78e';c.fillText('旅程尽头 · 誓印的去向',v.x+v.w/2,v.y+48);c.font='11px Courier New';c.fillStyle='#b9c9b2';this.drawTextBlock(c,`腐化 ${this.journeyConsequences.corruption}/3 · ${this.journeyConsequences.shortcutUsed?'已完成沉没捷径':'已完成四关旅程'}。可选结局来自本局真实誓印选择。`,v.x+v.w/2,v.y+80,v.w-28,16,2);for(const [i,r] of l.cards.entries()){c.fillStyle='#1e2c22';c.fillRect(r.x,r.y,r.w,r.h);c.strokeStyle='#a7b98d';c.strokeRect(r.x,r.y,r.w,r.h);c.font='bold 14px Courier New';c.fillStyle='#dfc78e';c.fillText((i+1)+' · '+r.name,r.x+r.w/2,r.y+24);c.font='11px Courier New';c.fillStyle='#c3ccb6';this.drawTextBlock(c,r.desc,r.x+r.w/2,r.y+47,r.w-26,16,3);}c.restore();}
 });
})();
