// Version-bound short trials, daily routes and eight-boss gauntlet.
const TrialModes={
 archer:{name:'贯箭试炼',hero:'ranger',theme:'frost',limit:480,desc:'仅弓箭构筑，8 分钟内击败寒霜首领。'},
 guard:{name:'守誓试炼',hero:'warden',theme:'village',limit:480,desc:'成功主动格挡 5 次，8 分钟内击败首领；只使用环绕武器。'},
 fire:{name:'归火试炼',hero:'arcanist',theme:'mine',limit:600,desc:'完成誓火搬运，10 分钟内击败矿洞首领。'},
 bossrush:{name:'八誓连战',limit:0,stages:['village','mine','frost','forest','hell','marsh','clock','court'],desc:'连续迎战八张地图的首领，关间恢复生命；不生成普通敌潮。'},
 daily:{name:'每日誓路',limit:0,desc:'固定版本、角色、种子与契约的四关旅程；只记录本地成绩。'}
};
const TrialRulesVersion=(document.currentScript?.src?.match(/\?v=(\d+\.\d+\.\d+-preview\.\d+)/)?.[1])||'0.23.0-preview.1';
(() => {
 const old={};for(const k of ['loadMeta','startNewGame','loadLevel','loadAndContinue','saveProgress','updatePlaying','update','getAvailableWeaponChoices','startVictorySequence','completeExploration','spawnEnemy','spawnElite','resetSave','getChallengeLayout','updateMenu','renderMenu','canShowRotateButton','renderHUD','renderEnding','updateLevelEncounters'])old[k]=Game[k];
 const finite=(v,max,fallback=0)=>Number.isFinite(v)?clamp(v,0,max):fallback;
 const hash=s=>Array.from(s).reduce((n,c)=>Math.imul(n^c.charCodeAt(0),16777619)>>>0,2166136261);
 Object.assign(Game,{
  runTrial:null,trialRandomState:0,_trialRandomDepth:0,
  createTrial(data){if(!TrialModes[data?.id])return null;const d=TrialModes[data.id];return {id:data.id,name:d.name,limit:d.limit,stages:d.stages?[...d.stages]:null,stageIndex:Math.floor(finite(data.stageIndex,7)),elapsed:finite(data.elapsed,100000),blocks:Math.floor(finite(data.blocks,5)),delivered:!!data.delivered,recorded:!!data.recorded,finishPending:!!data.finishPending,seed:Math.floor(finite(data.seed,0xffffffff)),hero:CONFIG.CHARACTERS[data.hero]?data.hero:d.hero||this.selectedCharacter,date:typeof data.date==='string'?data.date:'',rulesVersion:typeof data.rulesVersion==='string'?data.rulesVersion:TrialRulesVersion,code:typeof data.code==='string'?data.code:'',contracts:Array.isArray(data.contracts)?data.contracts.filter(id=>TrialContracts[id]):[]};},
  beginTrial(id){if(this.state!=='menu'||!TrialModes[id]||id==='daily'||id==='bossrush'&&!(this.meta.campaignClears>0))return false;this._pendingTrial={id,hero:TrialModes[id].hero||this.selectedCharacter,seed:Math.floor(Math.random()*0x7fffffff)};this._trialMenu=false;this._challengeMenu=false;this.startNewGame();return true;},
  makeDailyChallengeCode(date=new Date().toISOString().slice(0,10).replaceAll('-','')){if(!/^\d{8}$/.test(date))return null;const iso=date.slice(0,4)+'-'+date.slice(4,6)+'-'+date.slice(6,8),parsed=new Date(iso+'T00:00:00Z');if(!Number.isFinite(parsed.getTime())||parsed.toISOString().slice(0,10)!==iso)return null;const seed=hash(TrialRulesVersion+':'+date),hero=Object.keys(CONFIG.CHARACTERS)[seed%3];return `CB|${TrialRulesVersion}|${date}|${seed}|${hero}`;},
  beginDailyChallenge(code){if(this.state!=='menu'||!(this.meta.campaignClears>0)||typeof code!=='string')return false;const parts=code.trim().split('|');if(parts.length!==5||code.trim()!==this.makeDailyChallengeCode(parts[2]))return false;const seed=Number(parts[3]),ids=Object.keys(TrialContracts),first=seed%4,second=(first+1+(seed>>>8)%3)%4;this._pendingTrial={id:'daily',hero:parts[4],date:parts[2],seed,code:code.trim(),contracts:[ids[first],ids[second]]};this._trialMenu=false;this._challengeMenu=false;this.startNewGame();return true;},
  trialRandom(){let t=this.trialRandomState=(this.trialRandomState+0x6d2b79f5)>>>0;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;},
  withTrialRandom(fn){this._trialRandomDepth++;try{return fn();}finally{this._trialRandomDepth--; }},
  startNewGame(...a){const retry=this.state==='gameover'&&this.runTrial?{id:this.runTrial.id,hero:this.runTrial.hero,date:this.runTrial.date,seed:this.runTrial.seed,code:this.runTrial.code,contracts:this.runTrial.contracts}:null;this.runTrial=this.createTrial(this._pendingTrial||retry);this._pendingTrial=null;const mode=this.runTrial,selection={specs:{...this.selectedSpecializations},token:this.selectedStartingToken,contracts:[...this.selectedContracts],profile:this.selectedRunProfile};
   if(mode){this.selectedCharacter=mode.hero;this.selectedExpedition=mode.id==='daily'?'campaign':TrialModes[mode.id].theme||mode.stages[0];this.selectedSpecializations={warden:'',ranger:'',arcanist:''};this.selectedStartingToken='';this.selectedRunProfile='normal';if(mode.id==='daily')this.selectedContracts=[...mode.contracts];this.trialRandomState=mode.seed;}
   let result;try{result=this.withTrialRandom(()=>old.startNewGame.apply(this,a));if(mode){this.campaignMode=mode.id==='daily';if(mode.id==='archer'){this.player.weapons[0].level=3;this.restoreWeaponBranch(this.player.weapons[0],'bow_piercing');}if(mode.id==='guard')this.player.addWeapon('shield');if(mode.id==='bossrush'){for(const id of ['shield','dagger'])this.player.addWeapon(id);for(const w of this.player.weapons)w.level=6;this.player.stats.maxHpBonus+=60;this.player.stats.damageMult*=1.5;this.player.hp=this.player.getMaxHp();}this.saveProgress();}return result;}finally{if(mode){this.selectedSpecializations=selection.specs;this.selectedStartingToken=selection.token;this.selectedContracts=selection.contracts;this.selectedRunProfile=selection.profile;this.saveHeroJourneySelection();}}
  },
  getTrialLevel(theme){const base=CONFIG.LEVELS[theme],mode=this.runTrial;if(!mode||mode.id==='daily')return base;const boss=mode.id==='bossrush'?1:mode.limit-60;return {...base,challenge:true,bossSpawnTime:boss,phases:mode.id==='bossrush'?[]:base.phases.map(p=>p.events?.some(e=>e.type==='boss')?{...p,time:boss}:p)};},
  withTrialLevel(theme,fn){const base=CONFIG.LEVELS[theme];CONFIG.LEVELS[theme]=this.getTrialLevel(theme);try{return fn();}finally{CONFIG.LEVELS[theme]=base;}},
  loadLevel(id){const mode=this.runTrial,theme=mode&&mode.id!=='daily'?(TrialModes[mode.id].theme||mode.stages[mode.stageIndex]):id;if(mode?.id==='daily')this.runSeed=mode.seed;return this.withTrialLevel(theme,()=>this.withTrialRandom(()=>old.loadLevel.call(this,theme)));},
  saveProgress(){old.saveProgress.call(this);if(!this.player?.alive)return;try{const d=JSON.parse(localStorage.getItem(this.saveKey)||'null');if(d){d.runTrial=this.runTrial?{...this.runTrial}:null;d.trialRandomState=this.trialRandomState;localStorage.setItem(this.saveKey,JSON.stringify(d));}}catch{}},
  loadAndContinue(){let d;try{d=JSON.parse(localStorage.getItem(this.saveKey)||'null');}catch{}this.runTrial=this.createTrial(d?.runTrial);this.trialRandomState=Math.floor(finite(d?.trialRandomState,0xffffffff,this.runTrial?.seed||0));const result=this.withTrialLevel(CONFIG.LEVELS[d?.levelId]?d.levelId:'village',()=>this.withTrialRandom(()=>old.loadAndContinue.call(this)));this.trialRandomState=Math.floor(finite(d?.trialRandomState,0xffffffff,this.runTrial?.seed||0));if(this.runTrial?.recorded&&this.bossDefeated&&this.player.alive)this.state='victory';return result;},
  getAvailableWeaponChoices(...a){const choices=old.getAvailableWeaponChoices.apply(this,a);if(this.runTrial?.id==='archer')return choices.filter(c=>c.weaponId==='bow');if(this.runTrial?.id==='guard')return choices.filter(c=>CONFIG.WEAPONS[c.weaponId]?.type==='orbit');return choices;},
  spawnEnemy(...a){if(this.runTrial?.id==='bossrush')return;return old.spawnEnemy.apply(this,a);},
  spawnElite(...a){if(this.runTrial?.id==='bossrush')return;return old.spawnElite.apply(this,a);},
  updateLevelEncounters(...a){if(this.runTrial?.id==='bossrush')return;return old.updateLevelEncounters.apply(this,a);},
  completeExploration(s){const before=s.status;old.completeExploration.call(this,s);if(this.runTrial&&before==='active'&&s.status==='complete'&&this.exploration.kind==='carry'){this.runTrial.delivered=true;this.saveProgress();}},
  trialGoalMet(){const mode=this.runTrial;return !!mode&&(mode.id!=='guard'||mode.blocks>=5)&&(mode.id!=='fire'||mode.delivered);},
  completeTrialStage(){const mode=this.runTrial;if(!mode||!this.bossDefeated||!this.trialGoalMet()||!this.player.alive||mode.recorded)return false;if(mode.id==='bossrush'&&mode.stageIndex<7){mode.stageIndex++;mode.finishPending=false;this.runCoins+=10;this.loadLevel(mode.stages[mode.stageIndex]);this.saveProgress();return true;}this.state='victory';this.recordTrialResult(true);Audio2.playMusic('victory');this.saveProgress();return true;},
  failTrial(reason){if(!this.runTrial||this.runTrial.recorded)return;this.runTrial.failure=reason;this.state='gameover';this.player.alive=false;this.addMessage(reason,'#d69b80');this.recordTrialResult(false);Audio2.playMusic('gameover');},
  recordTrialResult(clear){const mode=this.runTrial;if(!mode||mode.recorded)return false;mode.recorded=true;this.meta.trialRecords=this.meta.trialRecords||{};const key=mode.id==='daily'?mode.code:mode.id+(this.runContracts.length?':'+[...this.runContracts].sort().join('.'):''),prior=this.meta.trialRecords[key]||{},seconds=mode.elapsed;this.meta.trialRecords[key]={attempts:(prior.attempts||0)+1,clears:(prior.clears||0)+(clear?1:0),bestSeconds:clear?Math.min(prior.bestSeconds||Infinity,seconds):prior.bestSeconds||null,version:mode.rulesVersion,lastResult:clear?'clear':'failed'};this.saveMeta();if(!clear){try{const saved=JSON.parse(localStorage.getItem(this.saveKey)||'null');if(saved?.runTrial?.id===mode.id&&saved.runTrial.seed===mode.seed)localStorage.removeItem(this.saveKey);}catch{}}return true;},
  updateTrialMode(dt){const mode=this.runTrial;if(!mode||mode.recorded)return;if(this.state==='playing'&&this.player?.alive){if(mode.finishPending&&this.bossDefeated){if(!this.completeTrialStage())this.failTrial('试炼目标未完成 · 先完成目标再迎战首领');return;}mode.elapsed+=dt;if(mode.limit&&this.levelTime>mode.limit&&!this.bossDefeated)this.failTrial('试炼超时 · 可重新挑战');}if(!this.player?.alive||this.state==='gameover')this.recordTrialResult(false);else if(this.state==='victory')this.recordTrialResult(true);},
  updatePlaying(dt){return this.withTrialRandom(()=>{old.updatePlaying.call(this,dt);this.updateTrialMode(dt);});},
  update(dt){old.update.call(this,dt);if(this.state!=='playing')this.updateTrialMode(0);},
  startVictorySequence(){if(this.runTrial&&this.runTrial.id!=='daily'){this.runTrial.finishPending=true;this.saveProgress();return;}return old.startVictorySequence.call(this);},
  loadMeta(){old.loadMeta.call(this);let d;try{d=JSON.parse(localStorage.getItem(this.metaKey)||'null');}catch{}this.meta.trialRecords={};for(const [key,r] of Object.entries(d?.trialRecords||{}).slice(-100))if(r&&typeof r==='object'&&Number.isFinite(r.attempts)&&Number.isFinite(r.clears))this.meta.trialRecords[key]={attempts:Math.floor(finite(r.attempts,100000)),clears:Math.floor(finite(r.clears,r.attempts)),bestSeconds:Number.isFinite(r.bestSeconds)?finite(r.bestSeconds,100000):null,version:typeof r.version==='string'?r.version:'unknown',lastResult:r.lastResult==='clear'?'clear':'failed'};},
  resetSave(){old.resetSave.call(this);this.runTrial=null;this._pendingTrial=null;this.meta.trialRecords={};},
  getChallengeLayout(){const v=this.getVisibleCanvasRect(),w=Math.min(580,v.w-28),x=v.x+(v.w-w)/2,h=Math.min(65,(v.h-232)/3);return {v,cards:Object.keys(RunProfiles).map((id,i)=>({id,x,y:v.y+96+i*(h+10),w,h})),trials:{x,y:v.y+v.h-80,w,h:30},back:{x,y:v.y+v.h-40,w,h:30}};},
  getTrialHubLayout(){const v=this.getVisibleCanvasRect(),w=Math.min(600,v.w-28),x=v.x+(v.w-w)/2,columns=v.w>=620&&v.h<500?2:1,h=columns===2?Math.min(110,(v.h-228)/2):Math.min(72,(v.h-240)/4),cw=(w-(columns-1)*8)/columns;return {v,tabs:['contracts','elites','trials','daily','records'].map((id,i)=>({id,x:x+i*(w+4)/5,y:v.y+72,w:(w-16)/5,h:30})),cards:[0,1,2,3].map(i=>({x:x+i%columns*(cw+8),y:v.y+126+Math.floor(i/columns)*(h+8),w:cw,h})),prev:{x,y:v.y+v.h-79,w:(w-8)/2,h:30},next:{x:x+(w+8)/2,y:v.y+v.h-79,w:(w-8)/2,h:30},back:{x,y:v.y+v.h-40,w,h:30}};},
  getTrialHubEntries(){const tab=this._trialTab||'contracts';if(tab==='contracts')return Object.entries(TrialContracts).map(([id,d])=>({id,...d,available:this.meta.campaignClears>0,selected:this.selectedContracts.includes(id),extra:this.meta.campaignClears>0?(this.selectedContracts.includes(id)?'已启用 · 下次普通旅程生效':'点击启用 · 可组合'):'完成四关旅程后解锁'}));
   if(tab==='elites')return Object.entries(EliteAffixes).map(([id,d])=>({id,...d,available:true,extra:'通关后的精英与契约追猎者可携带'}));
   if(tab==='trials')return ['archer','guard','fire','bossrush'].map(id=>({id,...TrialModes[id],available:id!=='bossrush'||this.meta.campaignClears>0,extra:id==='bossrush'&&!(this.meta.campaignClears>0)?'完成四关旅程后解锁':'点击开始 · 使用固定起始构筑'}));
   if(tab==='daily'){const code=this.makeDailyChallengeCode();return [{id:'start',name:'开始今日誓路',desc:'每日固定角色与两项契约，保留路线选择；不使用起始信物或专精。',available:this.meta.campaignClears>0,extra:this.meta.campaignClears>0?'点击开始今日旅程':'完成四关旅程后解锁'},{id:'import',name:'输入挑战码',desc:'重玩同版本、同一天的誓路；旧版本挑战码不能混用。',available:this.meta.campaignClears>0,extra:'点击输入 · 不存在全球排行榜'},{id:'share',name:'分享今日挑战码',desc:code,available:true,extra:'点击打开可复制文本'},{id:'record',name:'本地挑战记录',desc:'记录通关次数与最佳时间；没有服务器校验，成绩仅保存在本机。',available:true,extra:'点击查看记录'}];}
   const entries=Object.entries(this.meta.trialRecords||{}).reverse().map(([id,r])=>({id,name:id.startsWith('CB|')?'每日誓路 · '+id.split('|')[2]:(TrialModes[id.split(':')[0]]?.name||id),desc:`挑战 ${r.attempts} 次 · 通关 ${r.clears} 次 · ${r.bestSeconds===null?'暂无通关':`最佳 ${Math.floor(r.bestSeconds/60)}分${Math.floor(r.bestSeconds%60)}秒`}`,available:true,extra:r.version}));return entries.length?entries:[{id:'empty',name:'等待第一份记录',desc:'完成或失败一场精选试炼、每日誓路或首领连战后，会在这里留下记录。',available:true,extra:'普通旅程记录仍在难度与成就中'}];
  },
  updateMenu(){if(this._settingsOverlay)return old.updateMenu.call(this);if(this._trialMenu){const l=this.getTrialHubLayout();for(const r of l.tabs)if(Input.consumeClick(r.x,r.y,r.w,r.h)){this._trialTab=r.id;this._trialPage=0;return;}const entries=this.getTrialHubEntries(),page=this._trialPage||0;for(const [i,r] of l.cards.entries())if(Input.consumeClick(r.x,r.y,r.w,r.h)){const e=entries[page*4+i];if(!e?.available)return;if(this._trialTab==='contracts')this.selectTrialContract(e.id);else if(this._trialTab==='trials')this.beginTrial(e.id);else if(this._trialTab==='daily'){if(e.id==='start')this.beginDailyChallenge(this.makeDailyChallengeCode());else if(e.id==='import'){const code=window.prompt('输入同版本挑战码');if(code&&!this.beginDailyChallenge(code))this.addMessage('挑战码日期、版本或内容无效','#d3ab83');}else if(e.id==='share')window.prompt('复制今日挑战码',this.makeDailyChallengeCode());else {this._trialTab='records';this._trialPage=0;}}return;}
    if(Input.consumeClick(l.prev.x,l.prev.y,l.prev.w,l.prev.h))this._trialPage=Math.max(0,page-1);if(Input.consumeClick(l.next.x,l.next.y,l.next.w,l.next.h))this._trialPage=Math.min(Math.ceil(entries.length/4)-1,page+1);if(Input.wasPressed('Escape')||Input.consumeClick(l.back.x,l.back.y,l.back.w,l.back.h)){this._trialMenu=false;this._challengeMenu=true;}return;}
   if(this._challengeMenu){const r=this.getChallengeLayout().trials;if(Input.consumeClick(r.x,r.y,r.w,r.h)){this._challengeMenu=false;this._trialMenu=true;this._trialTab='contracts';this._trialPage=0;return;}}return old.updateMenu.call(this);
  },
  renderMenu(){old.renderMenu.call(this);if(this._settingsOverlay||!this._challengeMenu&&!this._trialMenu)return;const c=this.ctx;c.save();c.fillStyle='#101917';c.fillRect(0,0,960,540);c.textAlign='center';
   if(this._challengeMenu){const l=this.getChallengeLayout(),v=l.v;c.fillStyle='#dfc78e';c.font='bold 23px Courier New';c.fillText('远征挑战',v.x+v.w/2,v.y+40);c.font='10px Courier New';c.fillStyle='#a8bbaa';c.fillText('完成旅程解锁噩梦、铁誓、契约与首领连战',v.x+v.w/2,v.y+68);for(const r of l.cards){const d=RunProfiles[r.id],locked=r.id!=='normal'&&!(this.meta.campaignClears>0);this.drawButton(r.x,r.y,r.w,r.h,'',locked?'#788277':'#dfc78e');c.textAlign='center';c.fillStyle=locked?'#788277':'#dfc78e';c.font='bold 14px Courier New';c.fillText((locked?'锁定 · ':'')+d.name,r.x+r.w/2,r.y+20);c.font='10px Courier New';c.fillStyle='#a8bbaa';this.drawTextBlock(c,d.desc,r.x+r.w/2,r.y+39,r.w-20,12,2);}c.font='10px Courier New';c.fillText(`战役完成 ${this.meta.campaignClears||0} 次 · 成就 ${(this.meta.achievements||[]).length}/${Object.keys(RunAchievements).length}`,v.x+v.w/2,v.y+v.h-97);this.drawButton(l.trials.x,l.trials.y,l.trials.w,l.trials.h,'契约 / 精选试炼 / 每日誓路','#dfc78e');this.drawButton(l.back.x,l.back.y,l.back.w,l.back.h,'返回选择旅者','#a8bbaa');c.restore();return;}
   const l=this.getTrialHubLayout(),v=l.v,entries=this.getTrialHubEntries(),page=this._trialPage||0;c.fillStyle='#dfc78e';c.font='bold 23px Courier New';c.fillText('誓约试炼',v.x+v.w/2,v.y+38);c.font='10px Courier New';c.fillStyle='#a8bbaa';c.fillText('契约可组合 · 短试炼 8–10 分钟 · 本机记录',v.x+v.w/2,v.y+57);for(const r of l.tabs)this.drawButton(r.x,r.y,r.w,r.h,{contracts:'契约',elites:'精英',trials:'试炼',daily:'每日',records:'记录'}[r.id],this._trialTab===r.id?'#dfc78e':'#a8bbaa');
   for(const [i,r] of l.cards.entries()){const e=entries[page*4+i];if(!e)continue;c.fillStyle=e.selected?'#29382b':'#19241e';c.fillRect(r.x,r.y,r.w,r.h);c.strokeStyle=e.selected?'#dfc78e':e.available?'#5b6b5c':'#4b5049';c.strokeRect(r.x,r.y,r.w,r.h);c.textAlign='center';c.fillStyle=e.available?'#dfc78e':'#8b938a';c.font='bold 12px Courier New';c.fillText(this.fitChoiceBadgeText(c,(e.selected?'◆ ':'')+e.name,r.w-20),r.x+r.w/2,r.y+18);c.font='10px Courier New';c.fillStyle='#b4c2b1';this.drawTextBlock(c,e.desc,r.x+r.w/2,r.y+34,r.w-20,12,2);c.fillStyle='#a1b695';c.fillText(this.fitChoiceBadgeText(c,e.extra,r.w-20),r.x+r.w/2,r.y+r.h-6);}
   this.drawButton(l.prev.x,l.prev.y,l.prev.w,l.prev.h,'上一页','#a8bbaa');this.drawButton(l.next.x,l.next.y,l.next.w,l.next.h,`${page+1}/${Math.ceil(entries.length/4)} · 下一页`,'#a8bbaa');this.drawButton(l.back.x,l.back.y,l.back.w,l.back.h,'返回难度选择','#dfc78e');c.restore();
  },
  canShowRotateButton(){return !this._trialMenu&&old.canShowRotateButton.call(this);},
  renderHUD(){old.renderHUD.call(this);const mode=this.runTrial;if(!mode&&!this.runContracts.length)return;const c=this.ctx,v=this.getVisibleCanvasRect();let text=mode?.name||'契约 · '+this.runContracts.map(id=>TrialContracts[id].name).join(' / ');if(mode?.limit)text+=' · 剩 '+Math.max(0,Math.ceil(mode.limit-this.levelTime))+' 秒';if(mode?.id==='guard')text+=' · 格挡 '+mode.blocks+'/5';if(mode?.id==='fire')text+=mode.delivered?' · 誓火已送达':' · 需搬运誓火';if(mode?.id==='bossrush')text+=' · '+(mode.stageIndex+1)+'/8';c.save();c.font='10px Courier New';c.textAlign='center';c.fillStyle='#dfc78e';c.fillText(this.fitChoiceBadgeText(c,text,Math.min(450,v.w-24)),v.x+v.w/2,v.y+72);c.restore();},
  renderEnding(victory){const mode=this.runTrial;if(!mode)return old.renderEnding.call(this,victory);const c=this.ctx,l=this.getEndingLayout(),v=l.visible;c.save();c.fillStyle=victory?'#101b13':'#1c1413';c.fillRect(0,0,960,540);c.textAlign='center';const line=(text,y,size=12,color='#c6c3a0')=>{c.font=`${size}px Courier New`;c.fillStyle=color;c.fillText(this.fitChoiceBadgeText(c,text,l.w),l.cx,v.y+y);};line(mode.name+(victory?' · 完成':' · 止步'),64,v.w<420?25:34,victory?'#aed29c':'#dfab8c');c.font='12px Courier New';c.fillStyle='#c6c3a0';this.drawTextBlock(c,mode.failure||TrialModes[mode.id].desc,l.cx,v.y+108,l.w,18,2);line(`用时 ${Math.floor(mode.elapsed/60)}分${Math.floor(mode.elapsed%60)}秒 · 击杀 ${this.player.kills}`,166);line(mode.id==='bossrush'?`首领进度 ${mode.stageIndex+(victory?1:0)}/8`:`格挡 ${mode.blocks}/5 · 誓火 ${mode.delivered?'已送达':'未搬运'}`,194);line('契约 · '+(this.runContracts.map(id=>TrialContracts[id].name).join(' / ')||'无'),224,11);c.font='11px Courier New';c.fillStyle='#b8c9ad';this.drawTextBlock(c,this.player.weapons.map(w=>`${w.def.name} Lv.${w.level}`).join(' · '),l.cx,v.y+257,l.w,16,3);if(mode.id==='daily'){c.fillStyle='#b9c3d3';this.drawTextBlock(c,mode.code,l.cx,v.y+320,l.w,16,3);}line('成绩仅保存在本机 · 规则 '+mode.rulesVersion,386,10);if(!victory)this.drawButton(l.restart.x,l.restart.y,l.restart.w,l.restart.h,'重新挑战','#dfc78e');this.drawButton(l.menu.x,l.menu.y,l.menu.w,l.menu.h,'返回主菜单','#a8bbaa');c.restore();}
 });
 const random=Math.random;Math.random=function(){return Game.runTrial?.id==='daily'&&Game._trialRandomDepth>0?Game.trialRandom():random();};
 for(const key of ['generateUpgradeChoices','generateChestReward','selectUpgrade','selectChestReward','confirmWeaponReplacement','activateHeroSkill']){const method=Game[key];Game[key]=function(...a){return this.withTrialRandom(()=>method.apply(this,a));};}
 const take=Player.prototype.takeDamage;Player.prototype.takeDamage=function(...a){const blocked=this.activeSkill?.blocked,r=take.apply(this,a);if(!blocked&&this.activeSkill?.blocked&&Game.runTrial){Game.runTrial.blocks=Math.min(5,Game.runTrial.blocks+1);Game.saveProgress();}return r;};
})();
