import assert from 'node:assert/strict';
import {runtime} from './helpers/runtime.mjs';
const {run,storage}=runtime(['boss-combat','random-events','hero-skills','challenges','new-biomes','build-choices','weapon-branches','oath-relics','exploration','journey-shop','hero-journey','trial-contracts','trial-modes','blade-stance']);
run('Game.state="playing";Game.player.invuln=0;Game.enemies=[];Game.resetBladeStance();');
assert.equal(run('Game.activateBladeStance("outward")'),false,'Insufficient blade charge cannot activate');
run('Game.applyPlayerHitEffects({id:991,x:0,y:0},10,Game.player.weapons[0],Game.player,false,{secondary:true})');
assert.equal(run('Game.bladeStance.charge'),0,'Secondary effects do not generate charge');
run('Game.player.weapons[0].angle=0;const w=Game.player.weapons[0],e=new Enemy("skeleton",Game.player.x+w.getRange(),Game.player.y);e.hp=10000;Game.enemies=[e];Game.enemyGrid.clear();Game.enemyGrid.insert(e);w.update(0,Game.player);');
assert.equal(run('Game.bladeStance.charge'),4,'Actual orbital collision generates charge');
run('Game.bladeStance.charge=60;Game._normalRange=Game.player.weapons[0].getRange();Game._normalDamage=Game.player.weapons[0].getDamage();');
assert.equal(run('Game.activateBladeStance("outward")'),true);
assert.equal(run('Game.bladeStance.charge'),0);
assert.ok(run('Game.player.weapons[0].getRange()>Game._normalRange'),'Outward stance changes collision and draw radius');
assert.ok(run('Game.player.weapons[0].getDamage()>Game._normalDamage'));
run('Game.enemies=[];const w2=Game.player.weapons[0];w2.angle=0;w2.hitSet.clear();const outer=new Enemy("skeleton",Game.player.x+w2.getRange(),Game.player.y);outer.hp=10000;Game.enemies=[outer];Game.enemyGrid.clear();Game.enemyGrid.insert(outer);Game._outerHp=outer.hp;w2.update(0,Game.player);');
assert.ok(run('Game.enemies[0].hp<Game._outerHp'),'Expanded rendered orbit performs actual collisions at its new radius');
run('Game.enemies=[];Game.updateBladeStance(3.1)');
assert.equal(run('Game.bladeStance.mode'),'');
run('Game.bladeStance.charge=80;Game.activateBladeStance("inward");Game.player.invuln=0;Game._hp=Game.player.hp;Game.player.takeDamage(20);');
assert.equal(run('Game.player.hp'),run('Game._hp'),'Inward stance absorbs actual incoming damage');
assert.ok(run('Game.bladeStance.guard<36&&Game.bladeStance.guard>0'),'Absorption consumes a finite shield');
run('Game.player.invuln=0;Game.saveProgress();Game._shield=Game.bladeStance.guard;Game.loadAndContinue();');
assert.equal(run('Game.bladeStance.guard'),run('Game._shield'),'Reload restores consumed shield without refilling');
run('Game.state="paused";Game._remaining=Game.bladeStance.remaining;Game.updateBladeStance(2);');
assert.equal(run('Game.bladeStance.remaining'),run('Game._remaining'),'Pause freezes stance');
run('Game.state="playing";Game.loadLevel("mine")');
assert.equal(run('Game.bladeStance.guard'),run('Game._shield'),'Level transition retains remaining stance');
run('Game.bladeStance.charge=90;Game.startNewGame();');assert.equal(run('Game.bladeStance.charge'),0,'New run resets charge');
run('Game.resetBladeStance({charge:Infinity,mode:"invalid",guard:999,remaining:-1});');assert.equal(run('Game.bladeStance.guard'),0);assert.equal(run('Game.bladeStance.charge'),0);
assert.ok(storage.size>0);
run('Game.state="playing";Game.bladeStance.charge=50;Input._justPressed.KeyR=true;Game.updateBladeInput();delete Input._justPressed.KeyR;');assert.equal(run('Game.bladeStance.mode'),'outward','R activates outward stance');
assert.ok(run('Game.getBladeStanceButtons().every(r=>{const v=Game.getVisibleCanvasRect();return r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w&&r.y+r.h<=v.y+v.h;})'),'Both stance buttons fit visible canvas');
console.log('Blade charge uses real orbital hits; outward collision, finite inward guard, pause and resume passed.');
