import assert from 'node:assert/strict';
import {runtime} from './helpers/runtime.mjs';
const extras=['scene','boss-combat','random-events','hero-skills','challenges','new-biomes','build-choices','weapon-branches','oath-relics','exploration','journey-shop','hero-journey','trial-contracts','trial-modes','blade-stance','boss-oaths'];
const {run,storage}=runtime(extras);
run('Game.state="playing";Game.enemies=[];Game.resetBossOath();');
assert.equal(run('Game.chooseBossOath(true)'),false,'Cannot grant an oath before defeating a boss');
run('Game.onBossDefeated();Game.startVictorySequence();Game.updateBossOath(0);');
assert.equal(run('Game.state'),'bossOathChoice');
run('Game.saveProgress();Game.loadAndContinue();');assert.equal(run('Game.state'),'bossOathChoice','Pending oath reward survives actual save restore');
assert.equal(run('Game.chooseBossOath(true)'),true);assert.equal(run('Game.bossOath.owned'),'village');
assert.equal(run('Game.chooseBossOath(true)'),false,'Reward is consumed only once');
run('Game.state="bossOathChoice";Game.bossOath.pending={theme:"court",source:Game.bossOathSource(),deferred:true};');assert.equal(run('Game.chooseBossOath(true)'),false,'A pending reward must belong to the defeated map');run('Game.bossOath.pending=null;');
run('Game.state="playing";Game.player.activeSkill.active=0;Game.player.stats.armor=0;Game.player.invuln=0;Game.player.hp=Game.player.getMaxHp();Game._hp=Game.player.hp;Game.player.takeDamage(20);');assert.equal(run('Game._hp-Game.player.hp'),23,'Village oath increases actual incoming damage');
run('Game.loadLevel("mine");Game.state="playing";Game.onBossDefeated();Game.startVictorySequence();Game.updateBossOath(0);Game.chooseBossOath(true);');assert.equal(run('Game.bossOath.owned'),'mine','Later reward replaces previous oath');assert.equal(run('Game.getBossOathMultiplier("hurt")'),1,'Replacement removes previous penalty');
run('Game.state="playing";Game.environmentSpeedMult=1;Input.keys.KeyD=true;Game.player.dashTimer=0;Game._x=Game.player.x;Game.player.update(.01);Input.keys.KeyD=false;');assert.ok(run('Math.abs(Game.player.vx-CONFIG.PLAYER.speed*Game.player.stats.moveSpeedMult*.92)<.01'),'Mine penalty affects actual movement');
for(const id of ['village','mine','hell','frost','marsh','forest','clock','court']){
 run(`Game.state="playing";Game.resetBossOath({owned:${JSON.stringify(id)}});Game.bladeStance.remaining=0;Game.bladeStance.charge=60;Game.player.moveAngle=0;Game.enemies=[];Game._target=new Enemy("skeleton",Game.player.x+70,Game.player.y);Game._target.hp=10000;Game.enemies=[Game._target];Game._targetHp=Game._target.hp;`);
 assert.equal(run('Game.activateBladeStance("outward")'),true);
 assert.ok(run('Game.bossOath.fields.length>0'),`${id} activates a distinct ability`);
 for(let i=0;i<15;i++)run('Game.updateBossOath(.1)');
 assert.ok(run('Game.enemies[0].hp<Game._targetHp'),`${id} ability performs actual enemy damage`);
 assert.equal(run('Game.bladeStance.charge'),0,`${id} secondary ability does not refill blade charge`);
 assert.equal(run('Game.triggerBossOath()'),false,`${id} obeys its cooldown`);
}
run('Game.resetBossOath({owned:"hell"});Game.player.hp=50;Game.player.heal(10);');assert.equal(run('Game.player.hp'),58,'Healing downside changes actual healing');
run('Game.resetBossOath({owned:"frost"});Game._bow=new Weapon("bow",CONFIG.WEAPONS.bow);Game._cool=Game._bow.getCooldown();Game.resetBossOath();');assert.ok(run('Math.abs(Game._cool-Game._bow.getCooldown()*1.1)<.001'),'Frost downside changes weapon cooldown');
run('Game.resetBossOath({owned:"marsh"});Game._dmg=Game.player.weapons[0].getDamage();Game.resetBossOath();');assert.ok(run('Math.abs(Game._dmg-Game.player.weapons[0].getDamage()*.9)<.001'),'Marsh downside changes actual weapon damage');
run('Game.resetBossOath({owned:"forest"});Game.player.dashCooldown=0;Input._justPressed.Space=true;Game.player.update(0);delete Input._justPressed.Space;');assert.equal(run('Game.player.dashCooldown'),run('CONFIG.PLAYER.dashCooldown*Game.player.stats.dashCooldownMult*1.2'),'Forest downside changes actual dash cooldown');
run('Game.resetBossOath({owned:"clock"});Game.player.stats.critChanceBonus=.1;Game._crit=Game.player.weapons[0].getCritChance();Game.resetBossOath();');assert.ok(run('Math.abs(Game._crit-Game.player.weapons[0].getCritChance()+.05)<.001'),'Clock downside changes critical chance');
run('Game.resetBossOath({owned:"court"});Game.player.activeSkill.active=0;Game.player.activeSkill.cooldown=0;Game.bossDefeated=false;Game.activateHeroSkill();');assert.ok(run('Math.abs(Game.player.activeSkill.cooldown-HeroSkills.get(Game.player).cooldown*1.2)<.001'),'Court downside changes actual skill cooldown');
run('Game.state="playing";Game.bladeStance.remaining=0;Game.bladeStance.charge=60;Game.activateBladeStance("outward");Game.saveProgress();Game._fields=JSON.stringify(Game.bossOath.fields);Game._cd=Game.bossOath.cooldown;Game.loadAndContinue();');assert.equal(run('JSON.stringify(Game.bossOath.fields)'),run('Game._fields'),'Ability trajectories resume exactly');
assert.equal(run('Game.bossOath.cooldown'),run('Game._cd'));
run('Game.state="paused";Game.updateBossOath(1);');assert.equal(run('Game.bossOath.cooldown'),run('Game._cd'),'Pause freezes oath cooldown');
run('Game.state="playing";Game.loadLevel("forest");');assert.equal(run('Game.bossOath.owned'),'court','Oath ownership crosses levels');assert.equal(run('Game.bossOath.fields.length'),0,'Old-map ability positions do not leak into next map');
run('Game.startNewGame();');assert.equal(run('Game.bossOath.owned'),'');
run('Game.resetBossOath({owned:"bad",cooldown:Infinity,fields:[{kind:"bad"}]});');assert.equal(run('Game.bossOath.fields.length'),0);assert.equal(run('Game.bossOath.cooldown'),0);
run('Game.state="playing";Game.resetBossOath({owned:"village"});Game.triggerBossOath();Game.bossOath.fields[0].damage=1;Game.enemies=[new Enemy("skeleton",Game.player.x,Game.player.y)];Game.updateBossOath(.05);Game.saveProgress();Game.loadAndContinue();Game.state="playing";Game._restoredHp=Game.enemies[0].hp;Game.updateBossOath(.05);');assert.equal(run('Game.enemies[0].hp'),run('Game._restoredHp'),'Reload remaps hit identities and does not repeat one-shot damage');
run('Game.resetBossOath();Game.bossDefeated=false;Game.onBossDefeated();Game.startVictorySequence();Game.state="chestReward";Game.updateBossOath(.1);');assert.equal(run('Game.state'),'chestReward','Pending oath does not overwrite an open chest reward');
run('Game.state="playing";Game.updateBossOath(0);');assert.equal(run('Game.state'),'bossOathChoice','Oath choice opens after rewards settle');
run('Game.state="menu";Game.meta.campaignClears=1;Game.beginDailyChallenge(Game.makeDailyChallengeCode("20261009"));Game.state="playing";Game.player.weapons=[];Game.player.invuln=999;Game.pickups=[];Game.spawnTimer=999;Game.resetBossOath({owned:"village"});Game.triggerBossOath();Game.enemies=[new Enemy("skeleton",Game.player.x,Game.player.y)];const originalOathDamage=Game.damageBossOath;Game.damageBossOath=function(...a){this._testedRandomDepth=this._trialRandomDepth;return originalOathDamage.apply(this,a);};Game.updatePlaying(.01);');assert.ok(run('Game._testedRandomDepth>0'),'Daily oath damage and drops stay in the version-bound random scope');
assert.ok(storage.size>0);console.log('Eight boss oath abilities, actual downsides, replacement, pending reward and trajectories resume passed.');
