import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({console,Math,window:{innerWidth:390,innerHeight:844},localStorage:{setItem(){},getItem(){return null;}}});
for(const file of ['config','core','entities','game','objectives','builds']) vm.runInContext(readFileSync(new URL(`../js/${file}.js`,import.meta.url),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
run(`Game.player=new Player(960,720);Game.messages=[];Audio2.click=()=>{};Game.saveMeta=()=>{};
Game.meta={unlockedWeapons:[],unlockedUpgrades:[]};Game.state='levelup';Game.pendingLevelUps=0;
const ids=Object.keys(CONFIG.WEAPONS);ids.slice(1,6).forEach(id=>Game.player.addWeapon(id));`);
assert.equal(run('Game.player.weapons.length'),6);
assert.equal(run('Game.player.addWeapon(ids[6])'),false,'Full slots reject additional weapons');
assert.equal(run("Game.player.addWeapon('sword')"),true,'Owned weapons still upgrade at capacity');
run('Game.upgradeChoices=[{weaponId:ids[6]}];Game.selectUpgrade(0)');
assert.equal(run('!!Game._weaponReplacement'),true,'Reward opens replacement before consumption');
const before=run('JSON.stringify(Game.player.weapons.map(w=>[w.id,w.level]))');
run('Game.cancelWeaponReplacement()');
assert.equal(run('JSON.stringify(Game.player.weapons.map(w=>[w.id,w.level]))'),before,'Cancel preserves all weapons');
assert.equal(run('Game.state'),'levelup');
run('Game.selectUpgrade(0);Game.confirmWeaponReplacement(2)');
assert.equal(run('Game.player.weapons[2].id'),run('ids[6]'));
assert.equal(run('Game.player.weapons.length'),6);
assert.equal(run('Game.state'),'playing');
run(`Game.state='levelup';Game.upgradeChoices=[CONFIG.UPGRADES.find(u=>u.id==='summoner_pact')];Game.selectUpgrade(0)`);
assert.equal(run('Game.player.upgradeLevels.summoner_pact||0'),0,'Pact stats are not applied before confirmation');
run('Game.cancelWeaponReplacement()');
assert.equal(run('Game.player.stats.summonDamageMult'),1);
run('Game.selectUpgrade(0);Game.confirmWeaponReplacement(3)');
assert.equal(run('Game.player.weapons[3].id'),'shadow_imp');
assert.equal(run('Game.player.upgradeLevels.summoner_pact'),1);
run(`Game.player.weapons[3]=new Weapon(ids[7],CONFIG.WEAPONS[ids[7]]);Game.player.ensureSummonPactWeapon()`);
assert.equal(run("Game.player.weapons.some(w=>w.id==='shadow_imp')"),false,'An intentionally replaced pact weapon is not silently restored');
run(`const evo=CONFIG.WEAPON_EVOLUTIONS[0];Game.player.weapons[0]=new Weapon(ids[8],CONFIG.WEAPONS[ids[8]]);Game.player.weapons[1]=new Weapon(evo.baseWeapon,CONFIG.WEAPONS[evo.baseWeapon]);Game.player.weapons[1].level=4;
Game.player.upgradeLevels[evo.relic]=evo.relicMinLevel;Game.chestRewardChoices=[{type:'evolution',...evo}];
Game.state='chestReward';Audio2.boss=()=>{};Game.shakeScreen=()=>{};Game.particles=[];Game.particlePool={obtain:()=>({})};Game.selectChestReward(0)`);
assert.equal(run('Game.player.weapons[1].id'),run('evo.resultWeapon'),'Evolution keeps its slot');
assert.equal(run('Game.player.weapons[1].level'),4,'Evolution preserves level');
assert.equal(run('Game.player.weapons.length'),6);
run(`const old=Game.migrateSave({schemaVersion:5,weapons:ids.slice(0,9).map(id=>({id,level:3}))})`);
assert.equal(run('old.weaponCapacity'),9,'Legacy saves preserve expanded inventory');
assert.equal(run('old.schemaVersion'),7);
for(const size of [[390,844],[320,568],[844,390],[1280,720]]) {
  run(`window.innerWidth=${size[0]};window.innerHeight=${size[1]};Game._buildPage=0;Game._buildTab='weapons'`);
  assert.ok(run(`(()=>{const l=Game.getBuildPanelLayout(),v=Game.getVisibleCanvasRect();return [l.back,l.prev,l.next,...l.rows,...l.tabs].every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w&&r.y+r.h<=v.y+v.h)})()`),'Controls remain in the visible canvas');
}
console.log('Build transactions, evolution, save migration and responsive geometry passed.');
