import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const storage=new Map(),drawing=new Proxy({}, {get:(o,k)=>k==='measureText'?s=>({width:String(s).length*8}):o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
const ctx=vm.createContext({console,Math,setTimeout:f=>f(),window:{innerWidth:1280,innerHeight:720},document:{createElement:()=>({getContext:()=>drawing})},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}});
for(const f of ['config','core','entities','game','objectives','builds','world','run-summary','expansion','campaign'])vm.runInContext(readFileSync(new URL(`../js/${f}.js`,import.meta.url),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
run(`Audio2.playMusic=()=>{};Audio2.syncVolumes=()=>{};Audio2.play=()=>{};Assets.get=()=>undefined;Game.pickupPool=new ObjectPool(Pickup,10);Game.particlePool=new ObjectPool(Particle,10);Game.damageNumberPool=new ObjectPool(DamageNumber,10);Game.startStory=(lines,done)=>done();`);
for(const middle of ['mine','frost'])for(const end of ['hell','marsh']){
  ctx.middle=middle;ctx.end=end;
  run('Game.selectedExpedition="campaign";Game.startNewGame();Game.bossDefeated=true;Game.levelTime=480;Game.startVictorySequence()');
  assert.equal(run('Game.state'),'routeChoice');
  assert.equal(run('Game.chooseCampaignRoute("hell")'),false,'Cannot skip stage two');
  run('Game.saveProgress();Game.state="menu";Game.loadAndContinue()');
  assert.equal(run('Game.state'),'routeChoice','Resume returns to pending route');
  const maxHp=run('Game.player.getMaxHp()'),damage=run('Game.player.stats.damageMult');
  assert.equal(run('Game.chooseCampaignRoute(middle)'),true);
  if(middle==='frost')assert.equal(run('Game.player.getMaxHp()'),maxHp+15);
  else assert.equal(run('Game.player.stats.damageMult'),damage*1.08);
  assert.equal(run('Game.levelData.theme'),middle);
  const stats=run('JSON.stringify(Game.player.stats)');
  assert.equal(run('Game.chooseCampaignRoute(middle)'),false,'No repeat rewards');
  run('Game.levelTime=240;Game.saveProgress();Game.state="menu";Game.loadAndContinue()');
  assert.equal(run('JSON.stringify(Game.player.stats)'),stats,'Route boon survives without duplication');
  assert.equal(run('Game.getRunSummary().levels.length'),2,'Challenge biome retains campaign history');
  run('Game.bossDefeated=true;Game.startVictorySequence()');
  assert.equal(run('Game.state'),'routeChoice');
  const speed=run('Game.player.stats.moveSpeedMult'),cooldown=run('Game.player.stats.cooldownMult');
  run('Game.chooseCampaignRoute(end);Game.levelTime=270;Game.bossDefeated=true;Game.startVictorySequence()');
  if(end==='marsh')assert.equal(run('Game.player.stats.moveSpeedMult'),speed*1.08);
  else assert.equal(run('Game.player.stats.cooldownMult'),cooldown*.92);
  assert.equal(run('Game.state'),'victory');
  assert.equal(run('Game.getRunSummary().levels.length'),3);
  run('Game.saveProgress();Game.loadAndContinue()');
  assert.equal(run('Game.state'),'victory','Finished campaign cannot restart boss or route');
}
run('Game.selectedExpedition="frost";Game.state="menu";Game.startNewGame();Game.bossDefeated=true;Game.startVictorySequence()');
assert.equal(run('Game.state'),'victory','Standalone expedition remains one stage');
run('Game.state="menu";Game.selectedExpedition="frost";Game.startNewGame();Game.saveProgress();Game.selectedExpedition="campaign";Game.loadAndContinue();Game.state="gameover";Game.startNewGame()');
assert.equal(run('Game.levelData.theme'),'frost','Independent expedition death after refresh restarts its own map');
assert.equal(run('Game.campaignMode'),false);
run('Game.selectedExpedition="campaign";Game.state="menu";Game.startNewGame();Game.campaignMode=false;Game.saveProgress();Game.loadAndContinue();Game.bossDefeated=true;Game.startVictorySequence()');
assert.equal(run('Game.levelData.theme'),'mine','Legacy save keeps linear progression');
run('Game.state="menu";Game.selectedCharacter="ranger";Game.selectedExpedition="campaign";Game.startNewGame();Game.bossDefeated=true;Game.startVictorySequence();Game.chooseCampaignRoute("frost");Game.state="gameover";Game.startNewGame()');
assert.equal(run('Game.levelData.theme'),'village','Campaign death restarts at village');
assert.equal(run('Game.player.characterId'),'ranger','Restart retains character');
assert.equal(run('Game.campaignRoute.length'),1,'Restart clears prior route');
assert.ok(run('Number.isFinite(Game.player.getMaxHp())&&Number.isFinite(Game.player.stats.moveSpeedMult)'));
console.log('Four campaign routes, pending/final saves, boons, accounting and standalone/legacy flow passed.');
