async page => {
 const checks=[],screenshots=[],errors=[],url=page.url();page.on('pageerror',e=>errors.push(String(e)));const check=(name,v,evidence=null)=>{checks.push({name,passed:!!v,mode:'real input + accelerated combat/save fixtures',evidence});if(!v)throw Error(name);};
 const click=async(r,touch=false)=>{const pos=await page.evaluate(r=>{const b=Game.canvas.getBoundingClientRect();return{x:b.left+(r.x+r.w/2)/960*b.width,y:b.top+(r.y+r.h/2)/540*b.height};},r);if(touch)await page.touchscreen.tap(pos.x,pos.y);else await page.mouse.click(pos.x,pos.y);await page.waitForTimeout(80);};
 const settle=async()=>{for(let i=0;i<35;i++){const s=await page.evaluate(()=>Game.state);if(s==='story'){await page.waitForFunction(()=>Game.storyTimer>.31);await page.keyboard.press('Space');}else if(s==='levelup'||s==='chestReward'){if(await page.evaluate(()=>!!Game._weaponReplacement))await click(await page.evaluate(()=>Game.getBuildPanelLayout().rows[0]));else await page.keyboard.press('Digit1');}else return;await page.waitForTimeout(65);}};
 try{
 await page.setViewportSize({width:1280,height:720});await page.goto(url);await page.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu');
 await page.evaluate(()=>{Game.meta.campaignClears=0;Game.meta.achievements=[];Game.saveMeta();});await click(await page.evaluate(()=>Game.getMenuLayout().challenge));await click(await page.evaluate(()=>Game.getChallengeLayout().cards[1]));check('Locked challenge cannot start',await page.evaluate(()=>Game._challengeMenu&&Game.selectedRunProfile==='normal'));await click(await page.evaluate(()=>Game.getChallengeLayout().back));
 const matrix=[];
 for(const hero of ['warden','ranger','arcanist'])for(const route of [['mine','hell'],['mine','marsh'],['frost','hell'],['frost','marsh']]){
  await page.evaluate(hero=>{Game.state='menu';Game.selectedCharacter=hero;Game.selectedExpedition='campaign';Game.selectedRunProfile='normal';Game.startNewGame();},hero);await settle();
  for(let stage=0;stage<3;stage++){
   await page.evaluate(()=>{Game.state='playing';Game.player.invuln=999;Game.spawnTimer=999;Game.enemies=[];Game.pickups=[];Game.levelTime=Game.levelData.bossSpawnTime;Game.bossSpawned=false;Game.spawnBoss();const b=Game.enemies.find(e=>e.isBoss);b.hp=1;b.x=Game.player.x+80;b.y=Game.player.y;Game.player.weapons[0].level=(CONFIG.WEAPON_MAX_LEVEL||6);Game.activateHeroSkill();});await settle();await page.evaluate(()=>Game.activateHeroSkill());
   for(let i=0;i<120;i++){await page.evaluate(()=>{const b=Game.enemies.find(e=>e.alive&&e.isBoss),w=Game.player.weapons[0];if(b){const shot=Game.projectiles.find(p=>p.alive);if(shot){b.x=shot.x+shot.vx*.02;b.y=shot.y+shot.vy*.02;}else {const r=w.def.type==='orbit'?w.getRange():65;b.x=Game.player.x+Math.cos(w.angle)*r;b.y=Game.player.y+Math.sin(w.angle)*r;}}});if(await page.evaluate(()=>Game.bossDefeated))break;await page.waitForTimeout(50);}
   check(`${hero}/${route.join('-')}/stage ${stage+1}: actual weapon/skill defeats boss`,await page.evaluate(()=>Game.bossDefeated));
   await page.evaluate(()=>{Game.bossDefeatedGraceTimer=0;Game._victoryPending=false;Game.finishCampaignStage();});
   if(stage<2){await page.waitForFunction(()=>Game.state==='routeChoice');await click(await page.evaluate(id=>Game.getCampaignRouteLayout().cards.find(r=>r.id===id),route[stage]));await settle();}
  }
  check(`${hero}/${route.join('-')}: final campaign and achievements`,await page.evaluate(()=>Game.state==='victory'&&Game.meta.achievements.includes(Game.player.characterId)));
  await page.evaluate(()=>Game.saveProgress());await page.reload();await page.waitForFunction(()=>Game.state==='menu');await click(await page.evaluate(()=>Game.getMenuLayout().continue));check(`${hero}/${route.join('-')}: final save survives refresh`,await page.evaluate(()=>Game.state==='victory'));matrix.push({hero,route,state:'victory',mode:'accelerated actual combat'});
 }
 await page.evaluate(()=>Game.state='menu');await click(await page.evaluate(()=>Game.getMenuLayout().challenge));await click(await page.evaluate(()=>Game.getChallengeLayout().cards[1]));await click(await page.evaluate(()=>Game.getMenuLayout().start));await settle();await page.waitForFunction(()=>Game.state==='playing');check('Unlocked nightmare uses real menu input',await page.evaluate(()=>Game.runProfile==='nightmare'));
 await page.evaluate(()=>{Game.enemies=[new Enemy('villager',Game.player.x+100,Game.player.y)];Game.applyRunProfile(Game.enemies[0]);Game.spawnTimer=999;Game.player.invuln=999;Game.saveProgress();});check('Nightmare scales enemies exactly once',await page.evaluate(()=>Game.enemies[0].maxHp===CONFIG.ENEMIES.villager.hp*1.35));
 await page.evaluate(()=>{Game.enemies=[new Enemy(Game.levelData.bossId,Game.player.x+200,Game.player.y)];const b=Game.enemies[0];Game.applyRunProfile(b);b.takeDamage(b.maxHp*.6,false,0,0,0);Game.bossSpawned=true;Game._savedBossHP=b.hp;Game.saveProgress();});const hp=await page.evaluate(()=>Game._savedBossHP);await page.reload();await page.waitForFunction(()=>Game.state==='menu');await click(await page.evaluate(()=>Game.getMenuLayout().continue));await page.evaluate(()=>Game.state='paused');check('Boss HP and phase restore with a safe recovery',await page.evaluate(hp=>{const b=Game.enemies.find(e=>e.isBoss);return b.hp===hp&&b.phase===2&&b.signatureEffects.length===0&&b.stateTimer>0;},hp));
 await page.evaluate(()=>{Game.state='playing';Game.player.invuln=0;Game.player.takeDamage(99999);});await page.waitForFunction(()=>Game.state==='gameover');await click(await page.evaluate(()=>Game.getGameOverButtons().restart));await settle();check('Death restart preserves selected challenge',await page.evaluate(()=>Game.runProfile==='nightmare'));
 await page.evaluate(()=>{Game.state='menu';Game.selectRunProfile('iron');});await click(await page.evaluate(()=>Game.getMenuLayout().start));await settle();check('Iron challenge limits capacity and healing',await page.evaluate(()=>{Game.player.hp=50;Game.player.heal(100);return Game.player.hp===50&&Game.player.weaponCapacity===3;}));
 await page.evaluate(()=>{Game.saveProgress();Game.state='menu';});await click(await page.evaluate(()=>Game.getMenuLayout().challenge));const path='output/playwright/v120/v170-challenges.png';await page.screenshot({path});screenshots.push(path);
 const v=await page.evaluate(()=>({badges:Game.meta.achievements,records:Object.keys(Game.meta.challengeRecords).length,clears:Game.meta.campaignClears}));check('Three heroes and four routes persist records without permanent stat bonuses',v.clears>=12&&v.records>=12&&['warden','ranger','arcanist','first'].every(id=>v.badges.includes(id)),v);const desktop=page,context=await page.context().browser().newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto(url);await page.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu');await click(await page.evaluate(()=>Game.getMenuLayout().challenge),true);check('Portrait touch opens challenge choices',await page.evaluate(()=>Game._challengeMenu));check('Portrait choice and back controls stay within visible bounds',await page.evaluate(()=>{const l=Game.getChallengeLayout(),v=l.v;return [...l.cards,l.back].every(r=>r.x>=v.x&&r.x+r.w<=v.x+v.w&&r.y>=v.y&&r.y+r.h<=v.y+v.h);}));const mobilePath='output/playwright/v120/v170-challenges-mobile.png';await page.screenshot({path:mobilePath});screenshots.push(mobilePath);await click(await page.evaluate(()=>Game.getChallengeLayout().cards[0]),true);check('Portrait touch selects normal and returns to hero menu',await page.evaluate(()=>!Game._challengeMenu&&Game.selectedRunProfile==='normal'));await context.close();page=desktop;check('No challenge runtime errors',errors.length===0,errors);await page.evaluate(()=>{Game._challengeMenu=false;Game.state='menu';});return{passed:true,checks,screenshots,errors,matrix,limits:['Boss HP and timers are accelerated; this is not a natural full-run matrix.']};
 }catch(e){return{passed:false,checks,screenshots,errors,failure:String(e.stack||e)};}
}
