import assert from 'node:assert/strict';
import {runtime} from './helpers/runtime.mjs';
const modules=['boss-combat','random-events','hero-skills','challenges','new-biomes','build-choices','weapon-branches','oath-relics','exploration','journey-shop','hero-journey'];
const {run,ctx,storage}=runtime(modules);
assert.equal(run('Object.keys(HeroTasks).length'),12);
assert.equal(run('Game.selectHeroSpecialization("counter")'),false,'Locked specialization cannot be selected');
run('Game.state="playing";Game.player.invuln=0;Game.player.activeSkill.cooldown=0;Game.activateHeroSkill();Game.player.takeDamage(20)');
assert.equal(run('Game.meta.heroTasks.blocks'),1,'Real successful block counts');
run('Game.player.takeDamage(20)');
assert.equal(run('Game.meta.heroTasks.blocks'),1,'One block activation cannot be counted twice');
for(let i=0;i<4;i++)run('Game.player.activeSkill.cooldown=0;Game.player.activeSkill.active=0;Game.activateHeroSkill();Game.player.takeDamage(20)');
assert.equal(run('Game.meta.heroTasks.blocks'),5);
run('Game.state="menu"');
assert.equal(run('Game.selectHeroSpecialization("counter")'),true);
run('Game.startNewGame();Game.player.invuln=0;Game.enemies=[];const victim=new Enemy("skeleton",Game.player.x+140,Game.player.y);victim.hp=victim.maxHp=1000;Game.enemies=[victim];Game.activateHeroSkill();Game.player.takeDamage(20)');
assert.ok(run('victim.hp<1000'),'Counter specialization reaches actual distant target');
run('Game.saveProgress();Game.selectedSpecializations.warden="";Game.loadAndContinue()');
assert.equal(run('Game.heroJourney.specialization'),'counter','Run specialization survives menu changes and reload');
run('Game.player.alive=false;Game.state="gameover";Game.updateMeta();Game.loadMeta()');
assert.equal(run('Game.meta.heroTasks.blocks'),5,'Death retains permanent progress');
run('Game.state="menu";Game.selectedCharacter="ranger";Game.meta.heroTasks.arrowHits=30;Game.meta.heroTasks.volley=1;Game.saveMeta();Game.selectHeroSpecialization("precision");Game.startNewGame();Game.enemies=[];Game.activateHeroSkill()');
assert.equal(run('Game.projectiles.length'),1);
assert.ok(run('Game.projectiles[0].damage>50&&Game.projectiles[0].pierce>=4'));
run('Game.state="menu";Game.selectHeroSpecialization("scatter");Game.startNewGame();Game.enemies=[];Game.activateHeroSkill()');
assert.equal(run('Game.projectiles.length'),5);
assert.ok(run('new Set(Game.projectiles.map(p=>p.angle)).size===5'));
run('Game.meta.heroTasks.anchors=2;Game.state="menu"');
assert.equal(run('Game.selectStartingToken("ward")'),true);
run('Game.startNewGame();const guard=Game.player.branchGuard;Game.saveProgress();Game.loadAndContinue()');
assert.equal(run('Game.player.branchGuard'),run('guard'),'Continue never regrants starter ward');
run('Game.meta.heroTasks.bursts=10;Game.meta.heroTasks.crowd=1;Game.state="menu";Game.selectedCharacter="arcanist";Game.selectStartingToken("");Game.selectHeroSpecialization("eruption");Game.startNewGame();Game.enemies=[];const distant=new Enemy("skeleton",Game.player.x+200,Game.player.y);distant.hp=distant.maxHp=1000;Game.enemies=[distant];Game.activateHeroSkill();Game.player.update(.65)');
assert.equal(run('distant.hp'),1000,'Extended charge does not burst at normal charge time');
run('Game.saveProgress();Game.loadAndContinue()');
assert.ok(run('Game.player.activeSkill.charge>.2'),'Reload retains longer specialization charge');
run('Game.enemies=[distant];Game.player.update(.4)');
assert.ok(run('distant.hp<1000'),'Extended burst applies actual larger-radius damage');
run('Game.state="menu";Game.selectHeroSpecialization("ritual");Game.startNewGame();Game.enemies=[];const ritualTarget=new Enemy("skeleton",Game.player.x+70,Game.player.y);ritualTarget.hp=ritualTarget.maxHp=1000;Game.enemies=[ritualTarget];Game.activateHeroSkill();Game.player.update(.7)');
assert.equal(run('ritualTarget.hp'),1000,'Ritual replaces instant burst');
run('Game.updateHeroJourney(.51)');
assert.ok(run('ritualTarget.hp<1000'),'Ritual field causes actual periodic damage');
run('Game.saveProgress();Game.loadAndContinue()');
assert.equal(run('Game.heroJourney.fields[0].kind'),'ritual');
const before=run('Game.heroJourney.fields[0].life');run('Game.state="paused";Game.updateHeroJourney(2)');assert.equal(run('Game.heroJourney.fields[0].life'),before);
run('Game.state="menu";Game.selectedCharacter="warden";Game.startNewGame();Game.player.invuln=0;Game.activateHeroSkill();const eliteContact=new Enemy("corrupted_knight",Game.player.x,Game.player.y);Game.enemies=[eliteContact];eliteContact.update(.01)');
assert.equal(run('Game.meta.heroTasks.eliteBlock'),1,'Actual elite contact block unlocks sanctuary');
run('Game.state="menu";Game.selectHeroSpecialization("sanctuary");Game.startNewGame();Game.player.invuln=0;Game.activateHeroSkill();Game.player.takeDamage(10);Game.updateHeroJourney(1.01)');
assert.equal(run('Game.player.branchGuard'),3,'Sanctuary creates usable guard without healing');
run('Game.player.x+=200;Game.updateHeroJourney(1.01)');assert.equal(run('Game.player.branchGuard'),3,'Leaving field stops guard supply');
run('Game.meta.heroTasks.arrowHits=0;Game.meta.heroTasks.volley=0;Game.state="menu";Game.selectedCharacter="ranger";Game.selectHeroSpecialization("");Game.startNewGame();Game.enemies=[];Game.activateHeroSkill();const arrow=Game.projectiles[1];arrow.pierce=4;const arrowVictims=[0,1,2].map(i=>{const e=new Enemy("skeleton",Game.player.x+10+i*3,Game.player.y);e.hp=e.maxHp=1000;Game.enemyGrid.insert(e);return e;});Game.enemies=arrowVictims;arrow.update(.01)');
assert.equal(run('Game.meta.heroTasks.arrowHits'),3,'Actual skill projectile collisions count distinct enemies');
assert.equal(run('Game.meta.heroTasks.volley'),1);
run('arrow.update(.001)');assert.equal(run('Game.meta.heroTasks.arrowHits'),3,'Projectile retry cannot count same enemy again');
run('Game.state="menu";Game.selectedCharacter="arcanist";Game.selectHeroSpecialization("");Game.startNewGame();Game.meta.heroTasks.crowd=0;Game.enemies=[0,1,2].map(i=>{const e=new Enemy("skeleton",Game.player.x+70+i*10,Game.player.y);e.hp=e.maxHp=1000;return e;});Game.activateHeroSkill();Game.player.update(.7)');
assert.equal(run('Game.meta.heroTasks.crowd'),1,'Actual burst against three enemies unlocks ritual');
for(const [theme,id] of [['village','anchors'],['mine','delivery'],['hell','vault']]){ctx.theme=theme;ctx.taskId=id;run('Game.loadLevel(theme);Game.state="playing";{const site=Game.exploration.sites[0];site.status="active";Game.completeExploration(site);}');assert.ok(run('Game.meta.heroTasks[taskId]>0'));const n=run('Game.meta.heroTasks[taskId]');run('Game.completeExploration(Game.exploration.sites[0])');assert.equal(run('Game.meta.heroTasks[taskId]'),n,'Completed objective cannot award twice');}
run('Game.state="menu";Game.selectedCharacter="warden";Game.startNewGame();Game.meta.heroTasks.branches=0;Game.player.weapons[0].level=3;Game.state="levelup";Game.upgradeChoices=[Game.branchChoice("sword_close")];Game.selectUpgrade(0)');
assert.equal(run('Game.meta.heroTasks.branches'),1,'Actual upgrade selection counts branch');
run('Game.saveProgress();Game.loadAndContinue()');assert.equal(run('Game.meta.heroTasks.branches'),1,'Restoring branch is not another unlock');
for(const theme of ['village','mine','frost']){ctx.theme=theme;run('Game.loadLevel(theme);Game.state="routeChoice";Game.bossDefeated=true;Game.runCoins=100;Game.openJourneyShop("camp");Game.buyJourneyOffer(1)');}
assert.equal(run('Game.meta.heroTasks.forge'),3,'Three committed shop purchases unlock forge token');
for(let i=0;i<3;i++)run('Game.state="playing";Game.bossDefeated=false;Game.onBossDefeated()');
assert.equal(run('Game.meta.heroTasks.bosses'),3);run('Game.onBossDefeated()');assert.equal(run('Game.meta.heroTasks.bosses'),3);
run('Game.meta.heroTasks.delivery=1;Game.meta.heroTasks.bosses=3;Game.meta.heroTasks.branches=2;Game.state="menu";Game.selectStartingToken("fire");Game.startNewGame();Game.activateHeroSkill()');
assert.equal(run('Game.heroJourney.fields.filter(f=>f.kind==="starterFire").length'),1);
run('Game.saveProgress();Game.loadAndContinue();Game.player.activeSkill.cooldown=0;Game.player.activeSkill.active=0;Game.activateHeroSkill()');
assert.equal(run('Game.heroJourney.fields.filter(f=>f.kind==="starterFire").length'),1,'Starter fire cannot fire again after continue');
run('Game.state="menu";Game.selectStartingToken("focus");Game.startNewGame();Game.activateHeroSkill()');assert.equal(run('Game.player.activeSkill.cooldown'),7);
run('Game.player.activeSkill.cooldown=0;Game.player.activeSkill.active=0;Game.activateHeroSkill()');assert.equal(run('Game.player.activeSkill.cooldown'),10,'Focus only discounts first activation');
run('Game.state="menu";Game.selectStartingToken("scout");Game.startNewGame();Game.updateHeroJourney(29);Game.loadLevel("mine");Game.state="playing";Game.updateHeroJourney(2);Game.updateThemeHazards(0)');assert.equal(run('Game.heroJourney.elapsed'),30,'Scout timer crosses stages without renewing');
run('Game.meta.heroTasks.bosses=0;Game.bossDefeated=false;const actualBoss=new Enemy("boss",Game.player.x+100,Game.player.y);Game.enemies=[actualBoss];actualBoss.takeDamage(99999,false,0,Game.player.x,Game.player.y)');assert.equal(run('Game.meta.heroTasks.bosses'),1,'Actual boss death increments progression');
run('Game.meta.heroTasks={};Game.loadHeroJourneyMeta({heroTasks:{blocks:NaN,anchors:99999},selectedSpecializations:{ranger:"counter"},startingToken:"invalid"})');
assert.equal(run('Game.meta.heroTasks.blocks'),0);assert.equal(run('Game.meta.heroTasks.anchors'),2);
assert.equal(run('Game.selectedSpecializations.ranger'),"");assert.equal(run('Game.selectedStartingToken'),"");
console.log('Hero specialization combat, task persistence, starter idempotency, field resume and legacy validation passed.');
