import assert from 'node:assert/strict';
import {runtime} from './helpers/runtime.mjs';
const {run,ctx}=runtime(['boss-combat','random-events','hero-skills','challenges','build-choices','weapon-branches','oath-relics']);
assert.equal(run('typeof Game.acquireOathRelic'),'function','Rule relics can be acquired');
run(`Game.state='playing';Game.player.x=800;Game.player.y=800;function victim(x,y,id){const e=new Enemy('skeleton',x,y);e.hp=e.maxHp=10000;e.id=id;return e;}function grid(es){Game.enemies=es;Game.enemyGrid.clear();for(const e of es)Game.enemyGrid.insert(e);}`);
assert.equal(run(`Game.acquireOathRelic('ember')`),true);
run(`const burning=victim(800,800,1);burning.burnTimer=2;burning.hp=1;grid([burning]);burning.takeDamage(2,false,0,800,800);const emberVictim=victim(810,800,2);grid([emberVictim]);Game.updateOathRelics(.51);`);
assert.ok(run('emberVictim.hp<10000'),'Fire seeds damage actual nearby enemies');
run(`emberVictim.burnTimer=2;emberVictim.hp=1;Game.oathRun.emberCooldown=0;Game.updateOathRelics(.51);`);
assert.equal(run('Game.oathRun.fields.length'),1,'Secondary fire kills cannot create more fire seeds');
run(`Game.acquireOathRelic('return');const w=Game.player.weapons[0];w.angle=0;const a=victim(850,800,3),b=victim(855,805,4),c=victim(860,800,5),between=victim(830,800,6);grid([a,b,c,between]);for(const e of [a,b,c])Game.applyPlayerHitEffects(e,100,w,Game.player,false);`);
assert.ok(run('between.hp<10000'),'Three orbit hits cause real return-path damage');
const hp=run('between.hp');run('Game.applyPlayerHitEffects(c,100,w,Game.player,false)');assert.equal(run('between.hp'),hp,'Return triggers only once per rotation');
assert.equal(run(`Game.acquireOathRelic('breaker')`),true);
run(`Game.player.characterId='warden';HeroSkills.reset(Game.player);Game.activateHeroSkill();Game.player.invuln=0;Game.player.takeDamage(20);`);
assert.ok(run('Game.oathRun.breakerTime>0'),'Actual successful block arms the shock');
run(`const shock=victim(860,800,7);grid([shock]);Game.applyPlayerHitEffects(shock,100,w,Game.player,false);`);assert.ok(run('shock.hp<10000'));assert.equal(run('Game.oathRun.breakerTime'),0);
assert.equal(run(`Game.acquireOathRelic('solitude')`),true);assert.equal(run('Game.player.weaponCapacity'),2);
run(`Game.player.activeSkill.active=0;const mirror=victim(850,800,8);grid([mirror]);Game.oathRun.mirrorCooldown=0;Game.updateOathRelics(.01);`);assert.ok(run('mirror.hp<10000'),'Limited loadout creates damaging mirror blades');
run(`Game.acquireOathRelic('spirit');for(let i=0;i<5;i++){const m=new Minion(800,800,1,0,.01,'#fff',30,'weapons/shadow_imp','test');m.update(.02);}Game.player.activeSkill.cooldown=0;Game.player.activeSkill.active=0;`);assert.equal(run('Game.oathRun.spiritCharges'),3);
run('Game.activateHeroSkill()');assert.equal(run('Game.oathRun.spiritCharges'),0);assert.ok(run('Game.oathRun.skillPower>1'));assert.equal(run('Game.activateHeroSkill()'),false);
run(`const empowered=victim(850,800,9);grid([empowered]);Game.player.invuln=0;Game.player.takeDamage(20);`);assert.ok(run('10000-empowered.hp>32*Game.player.stats.damageMult*1.5'),'Consumed spirit charges strengthen actual counterattack damage');
run(`Game.acquireOathRelic('greed');Game.runCoins=30;Game.oathRun.greedKills=0;for(let i=0;i<4;i++){const e=victim(800,800,20+i);e.hp=1;e.takeDamage(2,false,0,800,800);}`);assert.equal(run('Game.runCoins'),35,'Four ordinary kills yield exactly one extra coin');
run(`Game.oathRun.hunterTimer=.01;Game.bossSpawned=false;Game.updateOathRelics(.02);`);assert.equal(run('Game.enemies.filter(e=>e.oathHunter&&e.alive).length'),1);
run(`Game.saveProgress();Game.loadAndContinue();`);assert.equal(run('Game.oathRun.owned.length'),6);assert.equal(run('Game.player.weaponCapacity'),2,'Capacity limitation survives restore without compounding');assert.equal(run('Game.enemies.filter(e=>e.oathHunter&&e.alive).length'),1,'Refresh preserves the pursuing risk');
run(`for(let i=0;i<3;i++){Game.oathRun.hunterTimer=.01;Game.updateOathRelics(.02);}`);assert.equal(run('Game.enemies.filter(e=>e.oathHunter&&e.alive).length'),2,'Pursuers remain capped');
for(const id of ['ember','return','breaker','solitude','spirit','greed']){ctx.id=id;assert.equal(run('Game.acquireOathRelic(id)'),false,'No duplicate acquisition');}
run(`Game.state='menu';Game.startNewGame();`);assert.equal(run('Game.oathRun.owned.length'),0,'Relics belong to one run');
run(`Game.player.addWeapon('bow');Game.player.addWeapon('shadow_imp');`);assert.equal(run(`Game.acquireOathRelic('solitude')`),false,'Solitude cannot silently remove an existing loadout');
console.log('Six oath relics: actual hits, nonrecursive seeds, block, capacity, summon charges, greed and save passed.');
