async page=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.reload();await page.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu');
 const cdp=await page.context().newCDPSession(page);await cdp.send('HeapProfiler.collectGarbage');const before=await cdp.send('Runtime.getHeapUsage');
 const result=await page.evaluate(async()=>{
  Game.startNewGame();Game.state='playing';Game.player.invuln=999;Game.spawnTimer=999;Game.player.weaponCapacity=6;Game.player.weapons=[];for(const id of ['hammer_meteor','bow','ring_fire','shadow_imp','fireball','crossbow_compact']){Game.player.addWeapon(id);if(Game.player.weapons.at(-1))Game.player.weapons.at(-1).level=6;}if(Game.player.weapons.length!==6)throw Error('Stress requires six configured weapons');Game.enemies=[];Game.pickups=[];
  const keys=['villager','wild_dog','skeleton','spider'].filter(id=>CONFIG.ENEMIES[id]);for(let i=0;i<120;i++){const a=i*2.4,r=80+i%10*22,e=new Enemy(keys[i%keys.length],Game.player.x+Math.cos(a)*r,Game.player.y+Math.sin(a)*r);e.hp=e.maxHp=999999;Game.enemies.push(e);}
  const update=[],render=[],frames=[],counts=[],originalUpdate=Game.updatePlaying,originalRender=Game.render;let last=performance.now(),start=last;
  Game.updatePlaying=function(...a){const t=performance.now();try{return originalUpdate.apply(this,a);}finally{update.push(performance.now()-t);}};Game.render=function(...a){const t=performance.now();try{return originalRender.apply(this,a);}finally{render.push(performance.now()-t);}};
  try{await new Promise(resolve=>{const frame=t=>{frames.push(t-last);last=t;if(Game.state==='story')Game.state='playing';if(Game.state==='levelup')Game.selectUpgrade(0);if(Game.state==='chestReward')Game.selectChestReward(0);if(Math.floor((t-start)/10000)>counts.length-1)counts.push({seconds:(t-start)/1000,enemies:Game.enemies.length,projectiles:Game.projectiles.length,particles:Game.particles.length,minions:Game.minions.length,heap:performance.memory?.usedJSHeapSize||null});if(t-start>=90000)resolve();else requestAnimationFrame(frame);};requestAnimationFrame(frame);});}finally{Game.updatePlaying=originalUpdate;Game.render=originalRender;Game.state='menu';Game.enemies=[];Game.projectiles=[];Game.particles=[];Game.minions=[];}
  const stats=a=>{a.sort((x,y)=>x-y);return{samples:a.length,mean:a.reduce((s,x)=>s+x,0)/a.length,p95:a[Math.floor(a.length*.95)],max:a.at(-1)}};return{duration:90,fixture:'120 durable enemies with six level-6 weapons',update:stats(update),render:stats(render),frame:stats(frames.slice(2)),counts};
 });await cdp.send('HeapProfiler.collectGarbage');const after=await cdp.send('Runtime.getHeapUsage');await cdp.detach();return{passed:errors.length===0&&result.counts.every(s=>s.enemies<=180&&s.particles<=600&&s.projectiles<=1000&&s.minions<=100),checks:[{name:'90-second enemy-wave stress has bounded live entities and no runtime errors',passed:errors.length===0&&result.counts.every(s=>s.enemies<=180&&s.particles<=600&&s.projectiles<=1000&&s.minions<=100)}],screenshots:[],errors,...result,heap:{before:before.usedSize,after:after.usedSize,delta:after.usedSize-before.usedSize},strict60fps:result.frame.p95<=16.9,limits:['Desktop Chrome stress fixture; 90 seconds cannot establish hours-long or physical-phone stability. Frame timing depends on hardware and browser scheduling.']};
}
