import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const storage=new Map(),draw=new Proxy({}, {get:(o,k)=>k==='measureText'?s=>({width:String(s).length*8}):k.startsWith('create')?()=>({addColorStop(){}}):o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
const ctx=vm.createContext({console,Math,setTimeout:f=>f(),window:{innerWidth:1280,innerHeight:720},document:{createElement:()=>({getContext:()=>draw})},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}});
for(const f of ['config','core','entities','game','objectives','builds','world','run-summary','expansion','scene','campaign','boss-combat','random-events','hero-skills','challenges','new-biomes'])vm.runInContext(readFileSync(new URL(`../js/${f}.js`,import.meta.url),'utf8'),ctx);
const run=s=>vm.runInContext(`{${s}}`,ctx);
run(`Audio2.playMusic=()=>{};Audio2.syncVolumes=()=>{};Audio2.play=()=>{};Audio2.pickup=()=>{};Assets.get=()=>undefined;Game.pickupPool=new ObjectPool(Pickup,10);Game.particlePool=new ObjectPool(Particle,10);Game.damageNumberPool=new ObjectPool(DamageNumber,10);Game.startStory=(lines,done)=>done();Game.selectedExpedition='campaign';Game.startNewGame();Game.state='playing';Game.pickups=[];`);
assert.equal(run('typeof Game.collectAllChestPickups'),'function','Treasure magnet activates global chest attraction');
run(`Game.pickups=[new Pickup(200,200,'chest','chest',0),new Pickup(1500,900,'chest','chest',1),new Pickup(300,300,'chest','chest',2),new Pickup(300,320,'xp','xp_gem_small',1)];Game.pickups[0].objectiveId='camp';`);
assert.equal(run('Game.collectAllChestPickups()'),2);
assert.equal(run('Game.pickups[2].magnetized'),false,'Suspicious trap remains in place');
assert.equal(run('Game.pickups[3].magnetized'),false,'XP remains the XP magnet responsibility');
run('Game.saveProgress();Game.loadAndContinue()');
assert.equal(run('Game.pickups.filter(p=>p.magnetized).length'),2,'Attraction survives refresh');
assert.equal(run('Game.pickups[0].objectiveId'),'camp');
run(`Game.state='playing';Game.pickups[0].life=1;Game.pickups[0].update(2);`);
assert.equal(run('Game.pickups[0].alive'),true,'True chests cannot expire while awaiting retrieval');
run(`Game._opened=[];Game.openChest=(x,y,type,guaranteed)=>{Game._opened.push({type,guaranteed});Game.state='chestReward';};Game.pickups.forEach(p=>{if(p.type==='chest'&&p.value!==2){p.x=Game.player.x;p.y=Game.player.y;}});for(const p of Game.pickups)p.update(.016);`);
assert.equal(run('Game._opened.length'),1,'A frame opens only one reward');
run(`Game.state='playing';for(const p of Game.pickups)p.update(.016);`);
assert.equal(run('Game._opened.length'),2,'Next reward remains available');
assert.equal(run('Game._opened[0].guaranteed'),true,'Objective protection preserved');
assert.equal(run('Game._opened[1].type'),1,'Rarity preserved');
run(`Game.pickups[0].collect();`);
assert.equal(run('Game._opened.length'),2,'Collected chest cannot pay twice');
run(`Game.state='playing';Game.chestMagnetDropped=false;Game.pickups=[];ENEMY_DEATH_BEHAVIOR.maybeDropChestMagnet({x:200,y:200,isElite:true});`);
assert.equal(run('Game.pickups[0].type'),'chestMagnet','First elite guarantees a find');
run('Game.saveProgress();Game.loadAndContinue()');
assert.equal(run('Game.chestMagnetDropped'),true);
assert.equal(run('Game.pickups[0].type'),'chestMagnet','Uncollected new item survives save/continue');
assert.equal(run('Game.pickups[0].life'),90);
run(`Game.loadLevel('mine');Game.state='playing';Game.pickups=[];Game.player.kills=(Game.runStartKills||0)+50;ENEMY_DEATH_BEHAVIOR.maybeDropChestMagnet({x:200,y:200});`);
assert.equal(run('Game.pickups[0].type'),'chestMagnet','Stage transition resets first-drop guarantee; fifty kills suffice');
run(`Game.pickups=[];ENEMY_DEATH_BEHAVIOR.maybeDropChestMagnet({x:200,y:200,isBoss:true});`);
assert.equal(run('Game.pickups[0].type'),'chestMagnet','Boss guarantees treasure retrieval');
run(`Game.pickups=[];ENEMY_DEATH_BEHAVIOR.maybeDropChestMagnet({x:200,y:200,isBoss:true,isMimic:true});`);
assert.equal(run('Game.pickups.length'),0,'Mimics cannot create a magnet chain');
console.log('Global treasure retrieval, sequential rewards, exact saves, rarity/objective guarantees and drop availability passed.');
