import assert from 'node:assert/strict';
import {runtime} from './helpers/runtime.mjs';
const {run,ctx}=runtime(['boss-combat','random-events','hero-skills','challenges','new-biomes','build-choices','weapon-branches','oath-relics','exploration','journey-shop','hero-journey','trial-contracts','trial-modes']);
assert.equal(run('Game.beginTrial("unknown")'),false);
run('Game.state="menu"');assert.equal(run('Game.beginTrial("archer")'),true);
assert.equal(run('Game.player.characterId'),'ranger');assert.equal(run('Game.levelData.theme'),'frost');
assert.equal(run('Game.levelData.bossSpawnTime'),420);assert.equal(run('Game.runTrial.limit'),480);
assert.ok(run('Game.getAvailableWeaponChoices().every(c=>c.weaponId==="bow")'),'Archer trial restricts actual weapon pool');
run('Game.state="playing";Game.enemies=[];Game.levelTime=481;Game.updateTrialMode(0)');assert.equal(run('Game.state'),'gameover');
assert.equal(run('Game.meta.trialRecords.archer.attempts'),1);run('Game.updateTrialMode(0)');assert.equal(run('Game.meta.trialRecords.archer.attempts'),1,'Failure record is idempotent');
assert.equal(run('Game.hasSave()'),false,'Finished failed trial cannot resume an earlier snapshot to repeat rewards');
run('Game.state="menu";Game.beginTrial("guard");Game.state="playing";Game.bossDefeated=true;Game.runTrial.blocks=4');
assert.equal(run('Game.completeTrialStage()'),false,'Guard clear requires five real blocks');
run('Game.bossDefeated=false;Game.player.invuln=0;Game.activateHeroSkill();Game.player.takeDamage(20)');assert.equal(run('Game.runTrial.blocks'),5);
run('Game.bossDefeated=true;Game.completeTrialStage()');assert.equal(run('Game.state'),'victory');assert.equal(run('Game.meta.trialRecords.guard.clears'),1);
run('Game.saveProgress();Game.loadAndContinue()');assert.equal(run('Game.state'),'victory','Completed trial resumes ending instead of another battle');assert.equal(run('Game.meta.trialRecords.guard.clears'),1);
run('Game.state="menu";Game.beginTrial("fire");Game.state="playing";Game.bossDefeated=true');assert.equal(run('Game.completeTrialStage()'),false);
run('Game.bossDefeated=false;const trialFire=Game.exploration.sites[0];trialFire.status="active";Game.completeExploration(trialFire);Game.bossDefeated=true;Game.completeTrialStage()');assert.equal(run('Game.state'),'victory','Fire clear requires committed actual delivery');
run('Game.meta.campaignClears=1;Game.state="menu"');assert.equal(run('Game.beginTrial("bossrush")'),true);
assert.ok(run('Game.runTrial.stages.length===8&&Game.levelData.bossSpawnTime<2'));
run('Game.state="playing";Game.levelTime=1.1;Game.updatePhase(.01)');assert.ok(run('Game.enemies.some(e=>e.alive&&e.isBoss)'),'Bossrush actually spawns boss from its configured clock');
run('Game.state="playing";Game.bossDefeated=true;Game.completeTrialStage()');assert.equal(run('Game.runTrial.stageIndex'),1);assert.equal(run('Game.levelData.theme'),'mine');
run('Game.saveProgress();Game.loadAndContinue()');assert.equal(run('Game.runTrial.stageIndex'),1);assert.ok(run('Game.levelData.bossSpawnTime<2'));
const code=run('Game.makeDailyChallengeCode("20261009")');ctx.code=code;
run('Game.state="menu"');assert.equal(run('Game.beginDailyChallenge(code)'),true);
const seed=run('Game.runSeed'),hero=run('Game.player.characterId'),values=run('[Game.trialRandom(),Game.trialRandom(),Game.trialRandom()]');
run('Game.saveProgress();const savedRng=Game.trialRandomState;const expectedNext=Game.trialRandom();Game.loadAndContinue()');assert.equal(run('Game.trialRandomState'),run('savedRng'));assert.equal(run('Game.trialRandom()'),run('expectedNext'));
run('Game.state="menu";Game.beginDailyChallenge(code)');assert.equal(run('Game.runSeed'),seed);assert.equal(run('Game.player.characterId'),hero);assert.deepEqual(run('[Game.trialRandom(),Game.trialRandom(),Game.trialRandom()]'),values);
assert.equal(run('Game.beginDailyChallenge(code.replace("0.22.0-preview.1","0.21.0-preview.1"))'),false,'Challenge code binds game rules version');
assert.equal(run('Game.beginDailyChallenge("CB|0.22.0-preview.1|20260230|123|warden")'),false,'Impossible date is rejected');
run('Game.state="menu";Game.beginTrial("guard");Game.state="playing";Game.enemies=[];Game.pickups=[];Game.bossSpawned=true;Game.bossDefeated=true;Game.runTrial.blocks=5;Game.bossDefeatedGraceTimer=.001;Game.spawnChest(Game.player.x,Game.player.y,1);Game.updatePlaying(.02)');
assert.equal(run('Game.state'),'chestReward','Nearby boss reward remains selectable before ending');assert.equal(run('Game.runTrial.recorded'),false,'Finish cannot be overwritten by reward pickup');
run('Game.selectChestReward(0);Game.updatePlaying(.02)');assert.equal(run('Game.state'),'victory','Finish proceeds after real chest reward selection');
run('Game.state="menu";Game.beginDailyChallenge(code);Game.state="levelup";Game.saveProgress();const choiceRng=Game.trialRandomState;Game.generateUpgradeChoices();const dailyChoices=JSON.stringify(Game.upgradeChoices.map(c=>Game.choiceKey(c)));Game.trialRandomState=choiceRng;Game.generateUpgradeChoices()');assert.equal(run('JSON.stringify(Game.upgradeChoices.map(c=>Game.choiceKey(c)))'),run('dailyChoices'),'Upgrade UI uses saved daily random stream');
console.log('Three short trials, real goals, bounded records, eight-boss progression and daily seed resume passed.');
