async page=>{
 const url=page.url(),checks=[],errors=[],screenshots=[];page.on('pageerror',e=>errors.push(String(e)));
 const check=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
 const point=async(p,r)=>p.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);
 const click=async r=>{const p=await point(page,r);await page.mouse.click(p.x,p.y);};
 const settle=async()=>{for(let i=0;i<60;i++){const s=await page.evaluate(()=>Game.state);if(s==='story'){await page.waitForTimeout(340);await page.keyboard.press('Space');}else if(['levelup','chestReward'].includes(s)){await page.keyboard.press('Digit1');await page.waitForTimeout(100);}else return;}};
 const shot=async name=>{const f=`output/playwright/v120/v200-${name}.png`;await page.screenshot({path:f});screenshots.push(f);};
 const reload=async state=>{await page.reload();await page.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await page.evaluate(()=>Game.getMenuLayout().continue));await page.waitForFunction(s=>Game.state===s||s==='playing'&&['levelup','chestReward','story'].includes(Game.state),state);if(state==='playing'){await settle();await page.waitForFunction(()=>Game.state==='playing');}};
 const map=async theme=>{await page.evaluate(theme=>{Game.state='paused';Game.loadLevel(theme);},theme);await settle();await page.evaluate(()=>{Game.state='playing';Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.levelTime=65;Game.triggeredPhases=Game.inferTriggeredPhases(65,false);for(const s of Game.levelEncounters)s.status='expired';for(const s of Game.randomEvents)s.status='declined';const s=Game.exploration.sites[0];s.status='ready';Game.player.x=s.x;Game.player.y=s.y;});await page.waitForTimeout(100);};
 try{
  await page.goto(url);await page.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});await click(await page.evaluate(()=>Game.getMenuLayout().start));await page.waitForFunction(()=>Game.state!=='menu');await settle();
  await page.evaluate(()=>{for(let seed=1;seed<50;seed++){Game.runSeed=seed;Game.loadLevel('village');if(Game.randomEvents[0].kind==='merchant')break;}Game.state='playing';const s=Game.randomEvents[0];s.status='ready';Game.player.x=s.x;Game.player.y=s.y;Game.player.invuln=999;Game.runCoins=60;Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;});
  await page.keyboard.press('KeyE');await page.waitForFunction(()=>Game.state==='journeyShop');await shot('merchant');
  const time=await page.evaluate(()=>Game.levelTime);await page.waitForTimeout(200);check('Merchant shopping freezes actual stage time',await page.evaluate(t=>Game.levelTime===t,time));
  await click(await page.evaluate(()=>Game.getJourneyShopLayout().cards[1]));await page.waitForFunction(()=>Game.journeyStore.offers[1].sold);check('Actual forge purchase costs 10 coins and upgrades once',await page.evaluate(()=>Game.runCoins===50&&Game.player.weapons[0].level===2));
  await click(await page.evaluate(()=>Game.getJourneyShopLayout().cards[1]));await page.waitForTimeout(100);check('Repeated sold-card click does not charge again',await page.evaluate(()=>Game.runCoins===50&&Game.player.weapons[0].level===2));
  const stock=await page.evaluate(()=>JSON.stringify(Game.journeyStore.offers));await reload('journeyShop');check('Real refresh restores exact merchant stock',await page.evaluate(stock=>JSON.stringify(Game.journeyStore.offers)===stock,stock));
  await click(await page.evaluate(()=>Game.getJourneyShopLayout().cards[0]));await page.waitForFunction(()=>Game.oathRun.owned.length===1);check('Relic card grants the rule relic for 18 coins',await page.evaluate(()=>Game.runCoins===32));
  await click(await page.evaluate(()=>Game.getJourneyShopLayout().reroll));await page.waitForFunction(()=>Game.journeyStore.rerolls===0);await reload('journeyShop');check('Paid shop reroll and sold items survive refresh',await page.evaluate(()=>Game.runCoins===29&&Game.journeyStore.rerolls===0&&Game.journeyStore.offers[0].sold&&Game.journeyStore.offers[1].sold));
  await page.keyboard.press('Escape');await page.waitForFunction(()=>Game.state==='playing');check('Leaving merchant completes visit and resumes battle',await page.evaluate(()=>Game.randomEvents[0].status==='complete'));

  await map('village');check('Locked anchor reward cannot be retrieved by magnet',await page.evaluate(()=>{Game.collectAllChestPickups();return !Game.pickups.some(p=>p.objectiveId?.startsWith('explore'));}));
  await page.keyboard.press('KeyE');await page.waitForFunction(()=>Game.exploration.sites[0].status==='active');await shot('anchor');await page.waitForFunction(()=>Game.exploration.sites[0].status==='complete',null,{timeout:12000});
  check('Actual six-second channel closes anchor and unlocks reward',await page.evaluate(()=>Game.exploration.sites[0].claimed&&Game.getAnchorWeakening()===.15));await settle();
  check('Completed anchor reduces real boss signature damage',await page.evaluate(()=>{const b=new Enemy('boss',800,800);return BossCombat.make(b,Game.player,'knightLunge')[0].damage<b.damage*.85;}));
  await page.evaluate(()=>Game.saveProgress());await reload('playing');check('Anchor completion survives real reload',await page.evaluate(()=>Game.exploration.sites[0].status==='complete'&&Game.getAnchorWeakening()===.15));

  await map('mine');await page.keyboard.press('KeyE');await page.waitForFunction(()=>Game.exploration.sites[0].carrying);await shot('carry');
  check('Carried fire slows actual movement environment',await page.evaluate(()=>Game.environmentSpeedMult<=.8));
  const ward=await page.evaluate(()=>{Game.player.invuln=0;Game.player.branchGuard=0;Game.player.activeSkill.active=0;const hp=Game.player.hp;Game.player.takeDamage(10);Game.player.invuln=999;return {hp,now:Game.player.hp,guard:Game.exploration.sites[0].guard};});check('Fire ward absorbs an actual hit',ward.now===ward.hp&&ward.guard<20);
  await page.keyboard.press('KeyE');await page.waitForFunction(()=>!Game.exploration.sites[0].carrying);await page.keyboard.press('KeyE');await page.waitForFunction(()=>Game.exploration.sites[0].carrying);check('Drop and pickup do not recharge fire ward',await page.evaluate(g=>Game.exploration.sites[0].guard===g,ward.guard));
  await page.evaluate(()=>Game.saveProgress());await reload('playing');check('Carried fire position, deadline and ward restore',await page.evaluate(g=>Game.exploration.sites[0].carrying&&Game.exploration.sites[0].guard===g&&Game.exploration.sites[0].deadline>Game.levelTime,ward.guard));
  await page.evaluate(()=>{Game.player.invuln=999;Game.spawnTimer=999;Game.enemies=[];const s=Game.exploration.sites[0];Game.player.x=s.destination.x;Game.player.y=s.destination.y;});await page.waitForFunction(()=>Game.exploration.sites[0].status==='complete');check('Arrival at destination completes actual fire delivery',await page.evaluate(()=>Game.exploration.sites[0].claimed&&!Game.exploration.sites[0].carrying));await settle();

  await map('hell');await page.keyboard.press('KeyE');await page.waitForFunction(()=>Game.state==='explorationChoice');await shot('vault-risk');check('Vault risk panel freezes the world',await page.evaluate(()=>!Game.exploration.sites[0].claimed&&!Game.pickups.some(p=>p.objectiveId?.startsWith('explore'))));
  await click(await page.evaluate(()=>Game.getExplorationChoiceLayout().cards[0]));await page.waitForFunction(()=>Game.state==='playing');check('Risk choice spawns six actual guards and one burden',await page.evaluate(()=>Game.enemies.filter(e=>e.explorationId&&e.alive).length===6&&Game.oathRun.burden===1));
  await page.evaluate(()=>Game.saveProgress());await reload('playing');check('Vault guards and their deadline survive refresh',await page.evaluate(()=>Game.enemies.filter(e=>e.explorationId&&e.alive).length===6&&Game.exploration.sites[0].deadline>Game.levelTime));
  for(let i=0;i<80;i++){await settle();if(await page.evaluate(()=>Game.state==='oathReward'))break;await page.evaluate(()=>{Game.spawnTimer=999;Game.player.invuln=999;const w=Game.player.weapons[0];for(const e of Game.enemies.filter(e=>e.explorationId&&e.alive)){e.hp=1;e.x=Game.player.x+Math.cos(w.angle)*w.getRange();e.y=Game.player.y+Math.sin(w.angle)*w.getRange();}});await page.waitForTimeout(100);}
  await page.waitForFunction(()=>Game.state==='oathReward');await shot('relic-reward');check('Weapon main loop unlocks relic choice after clearing guards',await page.evaluate(()=>!Game.enemies.some(e=>e.explorationId&&e.alive)&&!Game.exploration.sites[0].claimed));
  const reward=await page.evaluate(()=>JSON.stringify(Game._oathReward));await reload('oathReward');check('Pending relic choices restore exactly',await page.evaluate(r=>JSON.stringify(Game._oathReward)===r,reward));
  const owned=await page.evaluate(()=>Game.oathRun.owned.length);await click(await page.evaluate(()=>Game.getOathRewardLayout().cards[0]));await page.waitForFunction(()=>Game.state==='playing');check('Actual reward selection grants exactly one new relic',await page.evaluate(n=>Game.oathRun.owned.length===n+1&&Game.exploration.sites[0].claimed,owned));check('Completed relic choice cannot grant again',await page.evaluate(()=>Game.selectOathReward(0)===false));
  await map('court');await page.keyboard.press('KeyE');await page.waitForFunction(()=>Game.state==='explorationChoice');await click(await page.evaluate(()=>Game.getExplorationChoiceLayout().cards[0]));await page.waitForFunction(()=>Game.state==='playing');await page.evaluate(()=>{Game.levelTime=Game.exploration.sites[0].deadline+1;Game.triggeredPhases=Game.inferTriggeredPhases(Game.levelTime,false);});await page.waitForFunction(()=>Game.exploration.sites[0].status==='expired');check('Timed optional failure leaves main journey playable',await page.evaluate(()=>Game.state==='playing'&&Game.player.alive&&!Game.exploration.sites[0].claimed));

  await page.evaluate(()=>{Game.state='menu';Game.selectedExpedition='campaign';Game.startNewGame();});await settle();await page.evaluate(()=>{Game.bossDefeated=true;Game.bossSpawned=true;Game.bossDefeatedGraceTimer=0;Game.runCoins=50;Game.oathRun.burden=1;Game.finishCampaignStage();});await page.keyboard.press('KeyC');await page.waitForFunction(()=>Game.state==='journeyShop');
  await click(await page.evaluate(()=>Game.getJourneyShopLayout().cards[2]));await page.waitForFunction(()=>Game.oathRun.burden===0);check('Camp purchase cleanses real movement penalty',await page.evaluate(()=>Game.journeyStore.offers[2].sold&&Game.runCoins===44));
  await reload('journeyShop');check('Camp transaction resumes before route selection',await page.evaluate(()=>Game.oathRun.burden===0&&Game.journeyStore.offers[2].sold));
  for(const size of [{width:390,height:844},{width:320,height:568},{width:844,height:390}]){
   await page.setViewportSize(size);await page.evaluate(()=>Game.resizeCanvas());check(`Shop cards and buttons fit ${size.width}x${size.height}`,await page.evaluate(()=>{const l=Game.getJourneyShopLayout(),v=l.v;return [...l.cards,l.reroll,l.leave].every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w&&r.y+r.h<=v.y+v.h)&&l.cards[2].y+l.cards[2].h<l.reroll.y;}));await shot(`camp-${size.width}`);
   await click(await page.evaluate(()=>Game.getJourneyShopLayout().leave));await page.waitForFunction(()=>Game.state==='routeChoice');check(`Routes and optional camp button fit ${size.width}`,await page.evaluate(()=>{const l=Game.getCampaignRouteLayout(),v=l.visible;return [...l.cards,l.camp,l.menu].every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w&&r.y+r.h<=v.y+v.h)&&l.cards.at(-1).y+l.cards.at(-1).h<l.camp.y;}));await shot(`routes-${size.width}`);
   await click(await page.evaluate(()=>Game.getCampaignRouteLayout().camp));await page.waitForFunction(()=>Game.state==='journeyShop');
  }
  await page.setViewportSize({width:1280,height:720});await page.evaluate(()=>Game.resizeCanvas());await click(await page.evaluate(()=>Game.getJourneyShopLayout().leave));await page.waitForFunction(()=>Game.state==='routeChoice');await click(await page.evaluate(()=>Game.getCampaignRouteLayout().cards[0]));await page.waitForFunction(()=>Game.levelData.theme==='mine');await settle();check('Camp exit followed by actual route selection loads next stage',await page.evaluate(()=>Game.levelData.theme==='mine'&&Game.campaignRoute.length===2));
  for(const rotated of [false,true]){
   const context=await page.context().browser().newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});try{const m=await context.newPage();m.on('pageerror',e=>errors.push(String(e)));await m.goto(url);await m.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});const tap=async r=>{const p=await point(m,r);await m.touchscreen.tap(p.x,p.y);};if(rotated){await tap(await m.evaluate(()=>Game.getRotateButtonRect()));await m.waitForFunction(()=>Game._rotate90);}
    await m.evaluate(()=>{Game.selectedExpedition='campaign';Game.startNewGame();Game.bossDefeated=true;Game.bossSpawned=true;Game.bossDefeatedGraceTimer=0;Game.runCoins=50;Game.finishCampaignStage();});await tap(await m.evaluate(()=>Game.getCampaignRouteLayout().camp));await m.waitForFunction(()=>Game.state==='journeyShop');await tap(await m.evaluate(()=>Game.getJourneyShopLayout().cards[1]));await m.waitForFunction(()=>Game.journeyStore.offers[1].sold);check(`${rotated?'Rotated':'Portrait'} native touch buys without dash/joystick`,await m.evaluate(()=>!Input.joystick.active&&Game.player.dashTimer<=0&&Game.player.weapons[0].level===2));await tap(await m.evaluate(()=>Game.getJourneyShopLayout().leave));await m.waitForFunction(()=>Game.state==='routeChoice');await tap(await m.evaluate(()=>Game.getCampaignRouteLayout().cards[0]));await m.waitForFunction(()=>Game.levelData.theme==='mine');check(`${rotated?'Rotated':'Portrait'} native touch continues route`,true);
   }finally{await context.close();}
  }
  check('Reused exploration props exist and load',await page.evaluate(()=>['props/campfire_burnt','props/shrine_stone_lit','items/chest'].every(id=>Assets.get(id)?.complete)));check('No browser runtime errors',errors.length===0);return{passed:true,checks,errors,screenshots};
 }catch(e){await shot('failure');return{passed:false,failure:String(e.stack||e),checks,errors,screenshots};}
 finally{await page.setViewportSize({width:1280,height:720});await page.evaluate(()=>{Game.resizeCanvas();Game.state='menu';});}
}
