async page=>{
 const checks=[],errors=[],screenshots=[],url=page.url();const context=await page.context().browser().newContext({viewport:{width:1280,height:720}}),p=await context.newPage();p.on('pageerror',e=>errors.push(String(e)));
 const check=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
 const click=async r=>{const point=await p.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);await p.mouse.click(point.x,point.y);await p.waitForTimeout(80);};
 const settle=async()=>{for(let i=0;i<50;i++){const s=await p.evaluate(()=>Game.state);if(s==='story'){await p.waitForTimeout(340);await p.keyboard.press('Space');}else if(['levelup','chestReward'].includes(s)){await p.keyboard.press('Digit1');await p.waitForTimeout(100);}else return;}};
 const start=async()=>{await click(await p.evaluate(()=>Game.getMenuLayout().start));await p.waitForFunction(()=>Game.state!=='menu');await settle();await p.evaluate(()=>{Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;});};
 const menu=async hero=>{await p.evaluate(hero=>{Game.state='menu';Game.selectedCharacter=hero;Game._heroJournal=false;},hero);};
 const journal=async tab=>{await click(await p.evaluate(()=>Game.getMenuLayout().journal));await click(await p.evaluate(tab=>Game.getHeroJournalLayout().tabs.find(r=>r.id===tab),tab));};
 const choose=async id=>{const index=await p.evaluate(id=>Game.getHeroJournalEntries().findIndex(e=>e.id===id),id);for(let i=0;i<Math.floor(index/4);i++)await click(await p.evaluate(()=>Game.getHeroJournalLayout().next));await click(await p.evaluate(i=>Game.getHeroJournalLayout().cards[i%4],index));};
 const back=async()=>await click(await p.evaluate(()=>Game.getHeroJournalLayout().back));
 const reload=async()=>{await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().continue));await p.waitForFunction(()=>Game.state!=='menu');await settle();};
 const shot=async name=>{const path=`output/playwright/v120/v210-${name}.png`;await p.screenshot({path});screenshots.push(path);};
 try{
  await p.goto(url);await p.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});await journal('specialization');await choose('counter');check('Locked specialization is visible and cannot be selected',await p.evaluate(()=>!Game.selectedSpecializations.warden&&Game.getHeroJournalEntries().find(e=>e.id==='counter').available===false));await back();await start();
  for(let i=0;i<5;i++){await p.evaluate(()=>{Game.state='playing';Game.player.invuln=0;Game.player.activeSkill.active=0;Game.player.activeSkill.cooldown=0;});await p.keyboard.press('KeyQ',{delay:60});await p.waitForFunction(()=>Game.player.activeSkill.active>0);await p.evaluate(()=>Game.player.takeDamage(20));}
  const blockProgress=await p.evaluate(()=>Game.meta.heroTasks.blocks);check(`Actual Q casts and blocks unlock counter (${blockProgress}/5)`,blockProgress===5);
  await p.evaluate(()=>{Game.player.invuln=0;Game.player.activeSkill.active=0;Game.player.takeDamage(9999);});await p.waitForFunction(()=>Game.state==='gameover');await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});check('Death and real refresh retain completed task',await p.evaluate(()=>Game.meta.heroTasks.blocks===5));
  await journal('specialization');await choose('counter');await shot('counter');await back();await start();await p.keyboard.press('KeyQ',{delay:60});await p.waitForFunction(()=>Game.player.activeSkill.active>0);await p.evaluate(()=>{Game.player.invuln=0;const e=new Enemy('skeleton',Game.player.x+140,Game.player.y);e.hp=e.maxHp=1000;Game.enemies=[e];Game._counterTarget=e;Game.player.takeDamage(20);});check('Counter specialization damages a real target outside normal range',await p.evaluate(()=>Game._counterTarget.hp<1000));await p.evaluate(()=>Game.saveProgress());await reload();check('Actual continue restores specialization and skill definition',await p.evaluate(()=>Game.heroJourney.specialization==='counter'&&HeroSkills.get(Game.player).name==='裂阵反击'));
  await p.evaluate(()=>{for(const [id,d] of Object.entries(HeroTasks))Game.meta.heroTasks[id]=d.target;Game.saveMeta();});
  for(const [hero,spec,count] of [['ranger','precision',1],['ranger','scatter',5]]){await menu(hero);await journal('specialization');await choose(spec);await back();await start();await p.keyboard.press('KeyQ',{delay:60});await p.waitForFunction(()=>Game.player.activeSkill.cooldown>0);check(`${spec} actual Q casts correct projectile pattern`,await p.evaluate(count=>Game.projectiles.filter(s=>s.heroJourneyTag).length===count,count));}
  await menu('arcanist');await journal('specialization');await choose('eruption');await back();await start();await p.keyboard.press('KeyQ',{delay:60});await p.waitForFunction(()=>Game.player.activeSkill.charge>0);await p.evaluate(()=>{Game.state='paused';Game.saveProgress();});const charge=await p.evaluate(()=>Game.player.activeSkill.charge);await reload();check('Extended charge survives actual refresh',await p.evaluate(charge=>Game.heroJourney.specialization==='eruption'&&Game.player.activeSkill.charge<=charge&&HeroSkills.get(Game.player).charge===.95,charge));
  await menu('arcanist');await journal('specialization');await choose('ritual');await back();await start();await p.keyboard.press('KeyQ',{delay:60});await p.waitForFunction(()=>Game.heroJourney.fields.some(f=>f.kind==='ritual'));await shot('ritual');await p.evaluate(()=>{Game.state='paused';Game.saveProgress();});await reload();check('Ritual field survives actual refresh',await p.evaluate(()=>Game.heroJourney.fields.some(f=>f.kind==='ritual')));
  await menu('warden');await journal('specialization');await choose('sanctuary');await back();await start();await p.keyboard.press('KeyQ',{delay:60});await p.waitForFunction(()=>Game.player.activeSkill.active>0);await p.evaluate(()=>{Game.player.invuln=0;Game.player.takeDamage(20);});await p.waitForFunction(()=>Game.player.branchGuard>0);check('Sanctuary actual block supplies usable guard',await p.evaluate(()=>Game.heroJourney.fields.some(f=>f.kind==='sanctuary')&&Game.player.branchGuard>0));
  for(const token of ['ward','fire','purse','forge','focus','scout']){await menu('warden');await journal('tokens');await choose(token);await back();await start();await p.evaluate(()=>{Game.state='paused';Game.saveProgress();});check(`${token} starter selection applies only to new run`,await p.evaluate(token=>Game.heroJourney.token===token&&(token!=='purse'||Game.runCoins===6)&&(token!=='forge'||Game.player.weapons[0].level===2)&&(token!=='ward'||Game.player.branchGuard>0),token));const snapshot=await p.evaluate(()=>({coins:Game.runCoins,level:Game.player.weapons[0].level,consumed:Game.heroJourney.tokenConsumed}));await reload();check(`${token} actual continue does not regrant starter`,await p.evaluate(s=>Game.runCoins===s.coins&&Game.player.weapons[0].level===s.level&&Game.heroJourney.tokenConsumed===s.consumed,snapshot));}
  await menu('warden');await journal('tasks');await click(await p.evaluate(()=>Game.getHeroJournalLayout().next));await click(await p.evaluate(()=>Game.getHeroJournalLayout().cards[1]));await back();await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});check('Task tracking selection survives actual refresh',await p.evaluate(()=>Game.trackedHeroTask==='crowd'));
  for(const [width,height] of [[390,844],[320,568],[844,390]]){await p.setViewportSize({width,height});await menu('warden');await journal('tasks');await shot('journal-'+width);check(`Journal fits ${width}x${height}`,await p.evaluate(()=>{const l=Game.getHeroJournalLayout(),v=l.v;return [...l.tabs,...l.cards,l.prev,l.next,l.back].every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w+.1&&r.y+r.h<=v.y+v.h+.1)&&l.cards.at(-1).y+l.cards.at(-1).h<l.prev.y;}));await back();}
  const touch=await context.browser().newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),tp=await touch.newPage();tp.on('pageerror',e=>errors.push(String(e)));await tp.goto(url);await tp.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});const rect=await tp.evaluate(()=>Game.getMenuLayout().journal),b=await tp.evaluate(()=>{const b=Game.canvas.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};});await tp.touchscreen.tap(b.x+(rect.x+rect.w/2)/960*b.w,b.y+(rect.y+rect.h/2)/540*b.h);await tp.waitForFunction(()=>Game._heroJournal);check('Native portrait touch opens journal without starting run',await tp.evaluate(()=>Game.state==='menu'&&!Game.player));await touch.close();
  check('No browser runtime errors',errors.length===0);return {passed:true,checks,errors,screenshots};
 }catch(e){const path='output/playwright/v120/v210-failure.png';await p.screenshot({path});screenshots.push(path);return {passed:false,failure:String(e),checks,errors,screenshots};}finally{await context.close();}
}
