async page=>{
 const url=page.url(),checks=[],errors=[],screenshots=[],context=await page.context().browser().newContext({viewport:{width:1280,height:720}}),p=await context.newPage();p.on('pageerror',e=>errors.push(String(e)));
 const check=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
 const click=async r=>{const q=await p.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);await p.mouse.click(q.x,q.y);await p.waitForTimeout(80);};
 const settle=async()=>{for(let i=0;i<70;i++){const s=await p.evaluate(()=>Game.state);if(s==='story'){await p.waitForTimeout(340);await p.keyboard.press('Enter');await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}else if(s==='bossOathChoice'){await p.keyboard.press('Digit2');await p.waitForTimeout(1100);}else if(['levelup','chestReward'].includes(s)){await p.keyboard.press('Digit1');await p.waitForTimeout(80);}else return;}};
 const hub=async tab=>{await p.evaluate(()=>{Game.state='menu';Game._trialMenu=false;Game._challengeMenu=false;Game._heroJournal=false;Game._settingsOverlay=false;});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await click(await p.evaluate(()=>Game.getMenuLayout().challenge));await click(await p.evaluate(()=>Game.getChallengeLayout().trials));await click(await p.evaluate(tab=>Game.getTrialHubLayout().tabs.find(r=>r.id===tab),tab));await p.waitForFunction(()=>Game._trialMenu&&!Game._settingsOverlay);};
 const start=async id=>{await hub('trials');const index=await p.evaluate(id=>Game.getTrialHubEntries().findIndex(e=>e.id===id),id);await click(await p.evaluate(i=>Game.getTrialHubLayout().cards[i],index));await p.waitForFunction(()=>Game.state!=='menu');await settle();await p.evaluate(()=>{Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;});};
 const reload=async()=>{await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().continue));await p.waitForFunction(()=>Game.state!=='menu');await settle();};
 const shot=async name=>{const path=`output/playwright/v120/v220-${name}.png`;await p.screenshot({path});screenshots.push(path);};
 const killBoss=async()=>{const stage=await p.evaluate(()=>Game.runTrial.stageIndex);await p.evaluate(()=>{Game.state='playing';Game.player.invuln=999;Game.levelTime=Game.levelData.bossSpawnTime+.1;});for(let i=0;i<100;i++){await settle();if(await p.evaluate(()=>Game.bossSpawned))break;await p.waitForTimeout(80);}await p.waitForFunction(()=>Game.bossSpawned);await settle();await p.evaluate(()=>{const b=Game.enemies.find(e=>e.alive&&e.isBoss);b.takeDamage(99999,false,0,Game.player.x,Game.player.y);Game.bossDefeatedGraceTimer=.02;});for(let i=0;i<90;i++){await p.waitForTimeout(80);await settle();if(await p.evaluate(stage=>['victory','gameover'].includes(Game.state)||Game.runTrial.stageIndex>stage,stage))return;}throw Error('Boss ending did not settle');};
 try{
  await p.goto(url);await p.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});await hub('contracts');await click(await p.evaluate(()=>Game.getTrialHubLayout().cards[0]));check('Uncleared profile cannot activate contracts',await p.evaluate(()=>Game.selectedContracts.length===0));
  await p.evaluate(()=>{Game.meta.campaignClears=1;Game.saveMeta();});for(const i of [0,1,3])await click(await p.evaluate(i=>Game.getTrialHubLayout().cards[i],i));await shot('contracts');check('Three actual toggles compose independent contracts',await p.evaluate(()=>Game.selectedContracts.length===3));await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});check('Contract selections survive actual refresh',await p.evaluate(()=>Game.selectedContracts.length===3));
  await p.evaluate(()=>{Game.selectedContracts=[];Game.meta.selectedContracts=[];Game.saveMeta();});await start('archer');check('Actual trial card starts restricted ranger build',await p.evaluate(()=>Game.runTrial.id==='archer'&&Game.player.characterId==='ranger'&&Game.player.weapons[0].branch==='bow_piercing'&&Game.getAvailableWeaponChoices().every(c=>c.weaponId==='bow')));await killBoss();await p.waitForFunction(()=>Game.state==='victory');await shot('archer-clear');check('Actual boss death completes archer trial once',await p.evaluate(()=>Game.meta.trialRecords.archer.clears===1));await p.evaluate(()=>Game.saveProgress());await reload();check('Completed trial refresh restores ending and one reward',await p.evaluate(()=>Game.state==='victory'&&Game.meta.trialRecords.archer.clears===1));
  await start('guard');for(let i=0;i<5;i++){await p.evaluate(()=>{Game.player.activeSkill.active=0;Game.player.activeSkill.cooldown=0;});await p.keyboard.press('KeyQ',{delay:60});await p.waitForFunction(()=>Game.player.activeSkill.active>0);await p.evaluate(()=>{Game.player.invuln=0;Game.player.takeDamage(20);Game.player.invuln=999;});}check('Real Q block sequence advances trial-local goal',await p.evaluate(()=>Game.runTrial.blocks===5));await killBoss();await p.waitForFunction(()=>Game.state==='victory');check('Guard goal and actual boss death clear trial',await p.evaluate(()=>Game.meta.trialRecords.guard.clears===1));
  await start('fire');await p.evaluate(()=>{Game.levelTime=65;Game.triggeredPhases=Game.inferTriggeredPhases(65,false);for(const s of Game.levelEncounters)s.status='expired';for(const s of Game.randomEvents)s.status='declined';const s=Game.exploration.sites[0];s.status='ready';Game.player.x=s.x;Game.player.y=s.y;});await p.keyboard.press('KeyE');await p.waitForFunction(()=>Game.exploration.sites[0].carrying);await p.evaluate(()=>{const s=Game.exploration.sites[0];Game.player.x=s.destination.x;Game.player.y=s.destination.y;});await p.waitForFunction(()=>Game.runTrial.delivered);await settle();check('Fire trial uses committed main-loop delivery',await p.evaluate(()=>Game.exploration.sites[0].status==='complete'));await killBoss();await p.waitForFunction(()=>Game.state==='victory');check('Fire goal and actual boss death clear trial',await p.evaluate(()=>Game.meta.trialRecords.fire.clears===1));
  await start('archer');await p.evaluate(()=>{Game.levelTime=481;Game.triggeredPhases=Game.inferTriggeredPhases(481,true);Game.bossSpawned=true;});await p.waitForFunction(()=>Game.state==='gameover');check('Timeout stores one failure and removes finished challenge save',await p.evaluate(()=>Game.meta.trialRecords.archer.attempts===2&&!Game.hasSave()));await shot('timeout');
  await start('bossrush');for(let i=0;i<8;i++){await killBoss();if(i<7){await p.waitForFunction(i=>Game.runTrial.stageIndex===i+1,i);await settle();if(i===2){await p.evaluate(()=>{Game.state='paused';Game.saveProgress();});await reload();check('Actual refresh retains fourth boss stage',await p.evaluate(()=>Game.runTrial.stageIndex===3&&Game.levelData.theme==='forest'));}}else await p.waitForFunction(()=>Game.state==='victory');}check('Eight actual boss deaths clear gauntlet',await p.evaluate(()=>Game.meta.trialRecords.bossrush.clears===1&&Game.runTrial.stageIndex===7));await shot('bossrush-clear');
  await hub('daily');const code=await p.evaluate(()=>Game.makeDailyChallengeCode('20261009'));p.once('dialog',d=>d.accept(code));await click(await p.evaluate(()=>Game.getTrialHubLayout().cards[1]));await p.waitForFunction(()=>Game.runTrial?.id==='daily');await settle();await p.evaluate(()=>{Game.state='paused';Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.saveProgress();});const daily=await p.evaluate(()=>({seed:Game.runSeed,hero:Game.player.characterId,rng:Game.trialRandomState,code:Game.runTrial.code}));await reload();await p.evaluate(()=>Game.state='paused');check('Imported daily code restores seed, role and random state',await p.evaluate(s=>Game.runSeed===s.seed&&Game.player.characterId===s.hero&&Game.trialRandomState===s.rng&&Game.runTrial.code===s.code,daily));check('Daily uses neutral starter and two fixed contracts',await p.evaluate(()=>!Game.heroJourney.specialization&&!Game.heroJourney.token&&Game.runContracts.length===2));
  await hub('daily');p.once('dialog',d=>d.accept('CB|0.21.0-preview.1|20261009|1|warden'));await click(await p.evaluate(()=>Game.getTrialHubLayout().cards[1]));check('Old-version code leaves player in menu',await p.evaluate(()=>Game.state==='menu'&&Game._trialMenu));
  await hub('elites');check('All four elite behaviors are explained in the game',await p.evaluate(()=>Game.getTrialHubEntries().length===4&&Game.getTrialHubEntries().every(e=>e.desc.length>10)));await shot('elites');
  for(const [width,height] of [[390,844],[320,568],[844,390]]){await p.setViewportSize({width,height});await p.evaluate(()=>Game.resizeCanvas());await hub('trials');await shot('hub-'+width);check(`Trial hub fits ${width}x${height}`,await p.evaluate(()=>{const l=Game.getTrialHubLayout(),v=l.v;return [...l.tabs,...l.cards,l.prev,l.next,l.back].every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w+.1&&r.y+r.h<=v.y+v.h+.1)&&l.cards.at(-1).y+l.cards.at(-1).h<l.prev.y;}));}
  for(const rotated of [false,true]){const touch=await context.browser().newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),tp=await touch.newPage();try{tp.on('pageerror',e=>errors.push(String(e)));await tp.goto(url);await tp.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});if(rotated){await tp.evaluate(()=>{Game.forcedLandscape=true;Game.resizeCanvas();});}const tap=async r=>{const q=await tp.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);await tp.touchscreen.tap(q.x,q.y);await tp.waitForTimeout(100);};await tap(await tp.evaluate(()=>Game.getMenuLayout().challenge));await tap(await tp.evaluate(()=>Game.getChallengeLayout().trials));await tap(await tp.evaluate(()=>Game.getTrialHubLayout().tabs.find(r=>r.id==='trials')));await tap(await tp.evaluate(()=>Game.getTrialHubLayout().cards[0]));await tp.waitForFunction(()=>Game.runTrial?.id==='archer'&&Game.state!=='menu');check(`Native touch launches trial ${rotated?'rotated':'portrait'}`,await tp.evaluate(rotated=>Game.player.characterId==='ranger'&&!!Game._rotate90===rotated,rotated));}finally{await touch.close();}}
  await p.setViewportSize({width:1280,height:720});await p.evaluate(()=>Game.resizeCanvas());await start('archer');await p.evaluate(()=>{Game.state='paused';const p=Game.player;Game.enemies=[];for(const [i,id] of Object.keys(EliteAffixes).entries()){const e=new Enemy('corrupted_knight',p.x-180+i*120,p.y-100);e.isElite=true;Game.assignEliteAffix(e,id);Game.enemies.push(e);}Game.state='playing';Game.player.invuln=999;Game.spawnTimer=999;});await p.waitForTimeout(100);await shot('elite-scene');check('Four distinct elite affixes render in real scene',await p.evaluate(()=>new Set(Game.enemies.filter(e=>e.alive).map(e=>e.affix?.id)).size===4));
  check('No browser runtime errors',errors.length===0);return {passed:true,checks,errors,screenshots};
 }catch(e){const path='output/playwright/v120/v220-failure.png';await p.screenshot({path});screenshots.push(path);return {passed:false,failure:String(e),snapshot:await p.evaluate(()=>({state:Game.state,trial:Game.runTrial,bossSpawned:Game.bossSpawned,bossDefeated:Game.bossDefeated,grace:Game.bossDefeatedGraceTimer})),checks,errors,screenshots};}finally{await context.close();}
}
