async page=>{
 const url=page.url(),checks=[],errors=[],screenshots=[],context=await page.context().browser().newContext({viewport:{width:1280,height:720}}),p=await context.newPage();p.on('pageerror',e=>errors.push(String(e)));
 const check=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
 const point=async(p,r)=>p.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);
 const click=async r=>{const q=await point(p,r);await p.mouse.click(q.x,q.y);await p.waitForTimeout(100);};
 const settle=async()=>{for(let i=0;i<60;i++){const s=await p.evaluate(()=>Game.state);if(s==='story'){await p.waitForTimeout(350);await p.keyboard.press('Enter');await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}else if(['levelup','chestReward'].includes(s)){await p.keyboard.press('Digit1');await p.waitForTimeout(100);}else return;}};
 const kill=async()=>{await p.evaluate(()=>{Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.levelTime=Game.levelData.bossSpawnTime+.1;});for(let i=0;i<100;i++){await settle();if(await p.evaluate(()=>Game.bossSpawned))break;await p.waitForTimeout(80);}await p.waitForFunction(()=>Game.bossSpawned);await settle();await p.evaluate(()=>{const b=Game.enemies.find(e=>e.alive&&e.isBoss);b.takeDamage(99999,false,0,Game.player.x,Game.player.y);Game.bossDefeatedGraceTimer=.02;});for(let i=0;i<80;i++){await p.waitForTimeout(80);await settle();if(await p.evaluate(()=>Game.state==='bossOathChoice'))break;}await p.waitForFunction(()=>Game.state==='bossOathChoice');};
 const shot=async name=>{const path=`output/playwright/v120/v230-${name}.png`;await p.screenshot({path});screenshots.push(path);};
 try{
  await p.goto(url);await p.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().start));await settle();await kill();check('Real campaign boss death offers oath before route',await p.evaluate(()=>Game.bossOath.pending.theme==='village'&&Game.bossDefeated));await shot('oath-choice');await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().continue));await p.waitForFunction(()=>Game.state==='bossOathChoice');check('Pending boss reward survives actual page refresh',true);
  await click(await p.evaluate(()=>Game.getBossOathChoiceLayout().accept));for(let i=0;i<70;i++){await p.waitForTimeout(100);await settle();if(await p.evaluate(()=>Game.state==='routeChoice'))break;}await p.waitForFunction(()=>Game.state==='routeChoice');check('Accepting oath continues existing route flow',await p.evaluate(()=>Game.bossOath.owned==='village'&&Game.bossOath.decisions.length===1));await click(await p.evaluate(()=>Game.getCampaignRouteLayout().cards.find(r=>r.id==='mine')));await p.waitForFunction(()=>Game.levelData.theme==='mine');await settle();check('Accepted oath remains active in next map',await p.evaluate(()=>Game.bossOath.owned==='village'));
  await kill();await p.keyboard.press('Digit1');for(let i=0;i<70;i++){await p.waitForTimeout(100);await settle();if(await p.evaluate(()=>Game.state==='routeChoice'))break;}await p.waitForFunction(()=>Game.state==='routeChoice');check('Later oath replaces ownership and removes old downside',await p.evaluate(()=>Game.bossOath.owned==='mine'&&Game.getBossOathMultiplier('hurt')===1&&Game.bossOath.decisions.at(-1).choice==='replace'));
  await click(await p.evaluate(()=>Game.getCampaignRouteLayout().cards[0]));await settle();await kill();await p.keyboard.press('Digit2');for(let i=0;i<70;i++){await p.waitForTimeout(100);await settle();if(await p.evaluate(()=>Game.state==='routeChoice'))break;}await p.waitForFunction(()=>Game.state==='routeChoice');check('Declining a later boss oath keeps previous ability and downside',await p.evaluate(()=>Game.bossOath.owned==='mine'&&Game.getBossOathMultiplier('move')===.92&&Game.bossOath.decisions.at(-1).choice==='decline'));
  for(const [width,height] of [[390,844],[320,568],[844,390]]){await p.setViewportSize({width,height});await p.evaluate(()=>{Game.resizeCanvas();Game.bossOath.pending={theme:'court',source:Game.bossOathSource(),deferred:true};Game.state='bossOathChoice';});await shot('oath-'+width);check(`Oath reward layout fits ${width}x${height}`,await p.evaluate(()=>{const l=Game.getBossOathChoiceLayout(),v=l.v;return [l.accept,l.decline].every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w+.1&&r.y+r.h<=v.y+v.h+.1)&&l.accept.y+l.accept.h<l.decline.y;}));}
  await p.setViewportSize({width:1280,height:720});await p.evaluate(()=>{Game.resizeCanvas();Game.state='menu';Game.startNewGame();});await settle();for(const id of ['village','mine','hell','frost','marsh','forest','clock','court']){await p.evaluate(id=>{Game.state='playing';Game.resetBossOath({owned:id});Game.bladeStance.remaining=0;Game.bladeStance.charge=60;Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.player.invuln=999;},id);await p.keyboard.press('KeyR');await p.waitForFunction(()=>Game.bossOath.uses===1);await p.evaluate(()=>Game.state='paused');await p.evaluate(()=>Game.state='playing');await shot('ability-'+id);await p.evaluate(()=>Game.state='paused');check(`${id} oath renders a live bounded ability`,await p.evaluate(()=>Game.bossOath.fields.length>0&&Game.bossOath.fields.length<=4&&Game.bossOath.cooldown>0));}
  for(const rotated of [false,true]){const touch=await context.browser().newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),tp=await touch.newPage();try{tp.on('pageerror',e=>errors.push(String(e)));await tp.goto(url);await tp.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});await tp.evaluate(rotated=>{Game.forcedLandscape=rotated;Game.resizeCanvas();Game.startNewGame();Game.state='playing';Game.bossDefeated=false;Game.onBossDefeated();Game.startVictorySequence();Game.updateBossOath(0);},rotated);const q=await point(tp,await tp.evaluate(()=>Game.getBossOathChoiceLayout().accept));await tp.touchscreen.tap(q.x,q.y);await tp.waitForFunction(()=>Game.bossOath.owned==='village');check(`Native oath reward touch ${rotated?'rotated':'portrait'} consumes once`,await tp.evaluate(()=>Game.bossOath.decisions.length===1&&!Game.bossOath.pending&&!Input.joystick.active));}finally{await touch.close();}}
  check('No oath browser errors',errors.length===0);return {passed:true,checks,errors,screenshots};
 }catch(e){const path='output/playwright/v120/v230-oath-failure.png';await p.screenshot({path});screenshots.push(path);return {passed:false,failure:String(e),checks,errors,screenshots,snapshot:await p.evaluate(()=>({state:Game.state,oath:Game.bossOath,theme:Game.levelData?.theme}))};}finally{await context.close();}
}
