async page=>{
 const url=page.url(),checks=[],errors=[],screenshots=[],context=await page.context().browser().newContext({viewport:{width:1280,height:720}}),p=await context.newPage();
 const check=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
 const point=async(tab,r)=>tab.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);
 const shot=async name=>{const paused=await p.evaluate(()=>Game.state==='paused');if(paused)await p.evaluate(()=>Game.state='playing');const path=`output/playwright/v120/v240-${name}.png`;await p.screenshot({path});screenshots.push(path);if(paused)await p.evaluate(()=>Game.state='paused');};
 const boot=async tab=>{tab.on('pageerror',e=>errors.push(String(e)));await tab.goto(url);await tab.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});};
 try{
  await boot(p);await p.evaluate(()=>{Game.selectedExpedition='campaign';Game.startNewGame();Game.state='playing';Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.player.invuln=999;Game.player.x=Game.mapMechanism.x;Game.player.y=Game.mapMechanism.y;});
  check('Village oil exists on a reachable safe path',await p.evaluate(()=>Game.mapMechanism.type==='oil'&&Game.isMechanismPathSafe(Game.mapMechanism)));
  await p.keyboard.press('KeyE');await p.waitForFunction(()=>Game.mapMechanism.phase==='warning');await p.evaluate(()=>Game.state='paused');await shot('oil-warning');
  check('Keyboard activates once with one-second warning',await p.evaluate(()=>Game.mapMechanism.charges===1&&Game.mapMechanism.timer>0&&Game.mapMechanism.timer<=1));
  await p.evaluate(()=>{const s=Game.mapMechanism;Game.state='playing';Game.player.x=s.x+Math.cos(s.angle)*70;Game.player.y=s.y+Math.sin(s.angle)*70;Game.player.invuln=0;Game._hp240=Game.player.hp;const e=new Enemy('skeleton',Game.player.x,Game.player.y);e.hp=10000;Game._enemy240=e;Game.enemies=[e];Game.updateMapMechanism(1.1);Game.state='paused';});
  check('Burning lane damages actual enemy and player',await p.evaluate(()=>Game._enemy240.hp<10000&&Game.player.hp<Game._hp240));await shot('oil-active');
  await p.evaluate(()=>{Game.state='playing';Game.saveProgress();Game.state='paused';});await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await p.evaluate(()=>{Game.loadAndContinue();Game.state='paused';});
  check('Page refresh retains consumed oil use and active fire',await p.evaluate(()=>Game.mapMechanism.type==='oil'&&Game.mapMechanism.charges===1&&Game.mapMechanism.phase==='active'));
  await p.evaluate(()=>{Game.state='playing';Game.player.invuln=999;Game.updateMapMechanism(5);Game.player.x=Game.mapMechanism.x;Game.player.y=Game.mapMechanism.y;Game.activateMapMechanism();Game.updateMapMechanism(6);Game.state='paused';});
  check('Oil cannot be activated a third time',await p.evaluate(()=>{Game.state='playing';const ok=Game.activateMapMechanism();Game.state='paused';return !ok&&Game.mapMechanism.charges===0;}));
  await p.evaluate(()=>{Game.loadLevel('mine');Game.state='playing';Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.player.invuln=999;Game.player.x=Game.mapMechanism.x;Game.player.y=Game.mapMechanism.y;});await p.keyboard.press('KeyE');await p.waitForFunction(()=>Game.mapMechanism.phase==='warning');await p.evaluate(()=>Game.state='paused');await shot('cart-warning');
  check('Mine cart uses a safe track and real interaction',await p.evaluate(()=>Game.mapMechanism.charges===1&&Game.isMechanismPathSafe(Game.mapMechanism)));
  await p.evaluate(()=>{const s=Game.mapMechanism,e=new Enemy('skeleton',s.x+Math.cos(s.angle)*80,s.y+Math.sin(s.angle)*80);e.hp=10000;Game.enemies=[e];Game._enemy240=e;Game.state='playing';Game.updateMapMechanism(1.1);Game.updateMapMechanism(.8);Game.state='paused';});
  check('Moving cart performs actual swept damage',await p.evaluate(()=>Game._enemy240.hp<10000&&Game.mapMechanism.distance>80));await shot('cart-active');
  check('Cart has solid player collision',await p.evaluate(()=>{const s=Game.mechanismPosition();Game.player.x=s.x;Game.player.y=s.y;Game.resolvePropCollision(Game.player);return dist(Game.player.x,Game.player.y,s.x,s.y)>=Game.player.radius+25;}));
  await p.evaluate(()=>{Game.state='menu';Game.startNewGame();Game.state='playing';Game.spawnTimer=999;Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.randomEvents=[{id:'rescue-browser',kind:'rescue',status:'active',progress:7.99,x:Game.player.x,y:Game.player.y,deadline:Game.levelTime+45,claimed:false}];Game.updateRandomEvents(.02);Game.state='paused';});
  check('Actual rescue completion records future merchant benefit once',await p.evaluate(()=>Game.journeyConsequences.rescuedMerchant&&Game.journeyConsequences.rescues.length===1));
  await p.evaluate(()=>{Game.state='routeChoice';Game.bossDefeated=true;Game.bossDefeatedGraceTimer=0;Game.runCoins=100;Game.openJourneyShop('camp');});await shot('rescued-camp');
  check('Camp shows discounted actual prices',await p.evaluate(()=>Game.journeyStore.offers[1].price===8&&Game.journeyStore.offers[1].basePrice===10));
  const buy=await point(p,await p.evaluate(()=>Game.getJourneyShopLayout().cards[1]));await p.mouse.click(buy.x,buy.y);await p.waitForTimeout(150);
  check('Native camp purchase deducts discounted cost',await p.evaluate(()=>Game.runCoins===92&&Game.journeyStore.offers[1].sold));
  await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await p.evaluate(()=>Game.loadAndContinue());
  check('Discounted purchase survives page refresh without resale',await p.evaluate(()=>Game.state==='journeyShop'&&Game.journeyStore.offers[1].sold&&Game.runCoins===92));
  await p.evaluate(()=>{Game.state='menu';Game.startNewGame();Game.state='playing';Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.player.invuln=999;for(const s of Game.exploration.sites){s.status='active';Game.player.x=s.x;Game.player.y=s.y;Game.updateExploration(6.01);}Game.state='routeChoice';});
  check('Actual anchor progress unlocks fourth first-camp route',await p.evaluate(()=>Game.journeyConsequences.shortcutUnlocked&&Game.getCampaignRouteOptions().length===4));
  for(const [width,height] of [[1280,720],[390,844],[320,568],[844,390]]){await p.setViewportSize({width,height});await p.evaluate(()=>Game.resizeCanvas());await shot('shortcut-'+width);check(`Four route cards fit ${width}x${height}`,await p.evaluate(()=>{const l=Game.getCampaignRouteLayout(),v=l.visible;return l.cards.every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w+.1&&r.y+r.h<=l.camp.y); }));}
  const route=await point(p,await p.evaluate(()=>Game.getCampaignRouteLayout().cards.find(r=>r.id==='marsh')));await p.mouse.click(route.x,route.y);await p.waitForFunction(()=>Game.levelData.theme==='marsh');await p.evaluate(()=>{Game.state='playing';Game.saveProgress();Game.state='paused';});await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await p.evaluate(()=>{Game.loadAndContinue();Game.state='paused';});
  check('Shortcut retains four-stage campaign after page refresh',await p.evaluate(()=>Game.campaignMode&&Game.campaignRoute.join(',')==='village,marsh'&&Game.getCampaignRouteOptions().join(',')==='hell'));
  await p.evaluate(()=>{Game.state='menu';Game.startNewGame();Game.state='playing';Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.onBossDefeated();Game.startVictorySequence();Game.updateBossOath(0);});await p.waitForFunction(()=>Game.state==='bossOathChoice');await shot('corruption-choice');await p.keyboard.press('Digit1');await p.waitForFunction(()=>Game.journeyConsequences.corruption===1);
  check('Legal native oath acceptance records future corruption once',await p.evaluate(()=>Game.bossOath.owned==='village'&&Game.journeyConsequences.corruption===1&&!Game.bossOath.pending));
  await p.evaluate(()=>{Game.loadLevel('mine');Game.state='playing';Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.updateJourneyConsequences(35.1);Game.state='paused';});
  check('Next-map pursuit provides a ten-second advance warning',await p.evaluate(()=>Game.journeyConsequences.warned&&Game.journeyConsequences.hunterTimer<=10&&Game.enemies.length===0));
  await p.evaluate(()=>{Game.state='playing';Game.updateJourneyConsequences(10);Game.state='paused';});await shot('corruption-hunter');
  check('Corruption spawns a real hunter with behavioral affix',await p.evaluate(()=>Game.enemies.some(e=>e.alive&&e.consequenceHunter&&e.affix.id==='hunter')));
  await p.evaluate(()=>{Game.state='playing';Game.saveProgress();Game.state='paused';});await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await p.evaluate(()=>{Game.loadAndContinue();Game.state='paused';});
  check('Pursuit refresh preserves one hunter and spawn count',await p.evaluate(()=>Game.enemies.filter(e=>e.consequenceHunter).length===1&&Game.journeyConsequences.huntersSpawned===1));
  for(const rotated of [false,true]){const tc=await context.browser().newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),tp=await tc.newPage();try{await boot(tp);await tp.evaluate(rotated=>{Game.forcedLandscape=rotated;Game.resizeCanvas();Game.startNewGame();Game.state='playing';Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.player.x=Game.mapMechanism.x;Game.player.y=Game.mapMechanism.y;},rotated);const q=await point(tp,await tp.evaluate(()=>Game.getEncounterActionButton()));await tp.touchscreen.tap(q.x,q.y);await tp.waitForFunction(()=>Game.mapMechanism.charges===1);check(`Native mechanism touch ${rotated?'rotated':'portrait'} consumes once`,await tp.evaluate(()=>Game.mapMechanism.phase==='warning'&&!Input.joystick.active));}finally{await tc.close();}}
  check('No v0.24 browser errors',errors.length===0);return {passed:true,checks,errors,screenshots};
 }catch(e){await shot('failure');return {passed:false,failure:String(e),checks,errors,screenshots,snapshot:await p.evaluate(()=>({state:Game.state,theme:Game.levelData?.theme,mechanism:Game.mapMechanism,consequences:Game.journeyConsequences}))};}finally{await context.close();}
}
