async page=>{
 const url=page.url(),checks=[],errors=[],screenshots=[],context=await page.context().browser().newContext({viewport:{width:1280,height:720}}),p=await context.newPage();p.on('pageerror',e=>errors.push(String(e)));
 const check=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
 const point=async r=>p.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);
 const click=async r=>{const q=await point(r);await p.mouse.click(q.x,q.y);await p.waitForTimeout(100);};
 const shot=async name=>{const path=`output/playwright/v120/v250-${name}.png`;await p.screenshot({path});screenshots.push(path);};
 const settle=async()=>{for(let i=0;i<25&&await p.evaluate(()=>Game.state==='story');i++){await p.waitForTimeout(350);await p.keyboard.press('Enter');}};
 const defeat=async accept=>{await p.evaluate(()=>{Game.state='playing';Game.enemies=[];Game.pickups=[];Game.player.invuln=999;Game.bossDefeated=false;Game.onBossDefeated();Game.startVictorySequence();Game.updateBossOath(0);});await p.waitForFunction(()=>Game.state==='bossOathChoice');await p.keyboard.press(accept?'Digit1':'Digit2');for(let i=0;i<40;i++){await settle();if(await p.evaluate(()=>['routeChoice','journeyEndingChoice'].includes(Game.state)))return;await p.waitForTimeout(100);}throw Error('oath-to-route timeout');};
 try{
  await p.goto(url);await p.waitForFunction(()=>typeof Game!=='undefined'&&Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().challenge));await p.waitForFunction(()=>Game._challengeMenu);await click(await p.evaluate(()=>Game.getChallengeLayout().trials));await p.waitForFunction(()=>Game._trialMenu);await click(await p.evaluate(()=>Game.getTrialHubLayout().tabs.find(r=>r.id==='trials')));await click(await p.evaluate(()=>Game.getTrialHubLayout().next));await p.waitForFunction(()=>Game._trialTab==='trials'&&Game._trialPage===1);await shot('extraction-entry');await click(await p.evaluate(()=>Game.getTrialHubLayout().cards[0]));await settle();await p.waitForFunction(()=>Game.extraction&&Game.state==='playing');
  check('Native trial-hub entry starts independent extraction',await p.evaluate(()=>!Game.runTrial&&!Game.campaignMode&&Game.levelData.theme==='marsh'&&Game.extraction.sites.length===4));
  await p.evaluate(()=>{Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.updateExtraction(90.1);Game.player.x=Game.extraction.sites[0].x;Game.player.y=Game.extraction.sites[0].y;});await p.keyboard.press('KeyE');
  check('Living guards prevent native fragment collection',await p.evaluate(()=>Game.extraction.shards===0&&Game.enemies.some(e=>e.extractionGuardId===0&&e.alive)));
  await p.evaluate(()=>{for(const e of Game.enemies.filter(e=>e.extractionGuardId===0))e.takeDamage(99999,false,0,Game.player.x,Game.player.y);Game.updateExtraction(.01);});await p.keyboard.press('KeyE');await p.waitForFunction(()=>Game.extraction.shards===1);check('Native E collects an actually unlocked fragment once',await p.evaluate(()=>Game.extraction.sites[0].status==='claimed'));await p.evaluate(()=>Game.saveProgress());await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().continue));await p.waitForFunction(()=>Game.extraction&&Game.state==='playing');check('Actual refresh retains carried fragment without banking it',await p.evaluate(()=>Game.extraction.shards===1&&Game.meta.extraction.shards===0));
  await p.evaluate(()=>{Game.player.invuln=999;Game.enemies=[];Game.pickups=[];Game.spawnTimer=999;Game.updateExtraction(480-Game.extraction.elapsed+.1);Game.player.x=Game.extraction.exit.x+90;Game.player.y=Game.extraction.exit.y;});check('Outside beacon interaction radius does not offer an active button',await p.evaluate(()=>!Game.getExtractionObjective().action&&!Game.openExtractionChoice()));await p.evaluate(()=>Game.player.x=Game.extraction.exit.x);await p.keyboard.press('KeyE');await p.waitForFunction(()=>Game.state==='extractionChoice');
  for(const [width,height] of [[1280,720],[390,844],[320,568],[844,390]]){await p.setViewportSize({width,height});await p.evaluate(()=>Game.resizeCanvas());await shot('extract-choice-'+width);check('Extraction title fits '+width+'x'+height+', actual text bounds',await p.evaluate(()=>{const c=Game.ctx,original=c.fillText,v=Game.getVisibleCanvasRect(),widths=[];c.fillText=function(text,x,y,...rest){if(y===v.y+62&&x===v.x+v.w/2)widths.push(this.measureText(text).width);return original.call(this,text,x,y,...rest);};try{Game.render();}finally{c.fillText=original;}return widths.length===1&&widths[0]<=v.w-28;}));check(`Extraction decision fits ${width}x${height}`,await p.evaluate(()=>{const l=Game.getExtractionChoiceLayout(),v=l.v;return [l.leave,l.stay].every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w+.1&&r.y+r.h<=v.y+v.h); }));}
  await p.keyboard.press('Digit2');await p.waitForFunction(()=>Game.extraction.continues===1&&Game.state==='playing');check('Continue decision raises pursuit risk without banking',await p.evaluate(()=>Game.extraction.hunterTimer<=15&&Game.meta.extraction.shards===0));await p.keyboard.press('KeyE');await p.waitForFunction(()=>Game.state==='extractionChoice');await p.keyboard.press('Digit1');await p.waitForFunction(()=>Game.extraction.channeling);await p.evaluate(()=>Game.updateExtraction(2));await p.evaluate(()=>{Game.player.x=Game.extraction.exit.x+100;Game.updateExtraction(.1);});check('Actual movement outside beacon interrupts extraction',await p.evaluate(()=>!Game.extraction.channeling&&Game.extraction.channel===0&&Game.state==='playing'));
  await p.evaluate(()=>{Game.player.x=Game.extraction.exit.x;Game.player.y=Game.extraction.exit.y;});await p.keyboard.press('KeyE');await p.waitForFunction(()=>Game.state==='extractionChoice');await p.keyboard.press('Digit1');await p.waitForFunction(()=>Game.extraction.channeling);await p.evaluate(()=>Game.updateExtraction(4.1));await p.waitForFunction(()=>Game.state==='victory');await shot('extraction-success');check('Actual channel completion banks one fragment once',await p.evaluate(()=>Game.meta.extraction.shards===1&&Game.meta.extraction.clears===1));await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().continue));await p.waitForFunction(()=>Game.state==='victory');check('Success refresh keeps receipt without duplicate reward',await p.evaluate(()=>Game.meta.extraction.shards===1&&Game.meta.extraction.clears===1));
  await p.evaluate(()=>{Game.state='menu';Game.beginTreasureExtraction();Game.state='playing';Game.updateExtraction(720.1);});await shot('extraction-failed');check('Deadline failure invalidates resumable checkpoint and no banked reward',await p.evaluate(()=>Game.state==='gameover'&&!localStorage.getItem(Game.saveKey)&&Game.meta.extraction.shards===1));
  await p.setViewportSize({width:1280,height:720});await p.evaluate(()=>{Game.state='menu';Game.selectedExpedition='campaign';Game.startNewGame();Game.state='playing';Game.player.invuln=999;Game.enemies=[];for(const s of Game.exploration.sites){s.status='active';Game.player.x=s.x;Game.player.y=s.y;Game.updateExploration(6.01);}});await defeat(true);await click(await p.evaluate(()=>Game.getCampaignRouteLayout().cards.find(r=>r.id==='marsh')));await settle();await defeat(false);await click(await p.evaluate(()=>Game.getCampaignRouteLayout().cards.find(r=>r.id==='hell')));await settle();await defeat(false);await click(await p.evaluate(()=>Game.getCampaignRouteLayout().cards.find(r=>r.id==='court')));await settle();await defeat(false);
  check('Actual hidden journey and oath choices offer two legal endings',await p.evaluate(()=>Game.hasLegalEndingJourney()&&Game.getJourneyEndingEntries().length===2));
  for(const [width,height] of [[1280,720],[390,844],[320,568],[844,390]]){await p.setViewportSize({width,height});await p.evaluate(()=>Game.resizeCanvas());await shot('ending-choice-'+width);check(`Journey ending choices fit ${width}x${height}`,await p.evaluate(()=>{const l=Game.getJourneyEndingLayout(),v=l.v;return l.cards.every(r=>r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w+.1&&r.y+r.h<=v.y+v.h); }));}
  await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().continue));await p.waitForFunction(()=>Game.state==='journeyEndingChoice');check('Unchosen ending survives actual page refresh',true);await click(await p.evaluate(()=>Game.getJourneyEndingLayout().cards.find(r=>r.id==='purify')));await p.waitForFunction(()=>Game.state==='victory');await shot('hidden-purification');check('Native purification commits hidden ending and removes borrowed ability',await p.evaluate(()=>Game.journeyEnding.id==='purify'&&Game.journeyEnding.hidden&&!Game.bossOath.owned&&Game.meta.journeyEndings.purify===1));await p.reload();await p.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await click(await p.evaluate(()=>Game.getMenuLayout().continue));await p.waitForFunction(()=>Game.state==='victory');check('Ending refresh preserves single receipt',await p.evaluate(()=>Game.meta.journeyEndings.purify===1&&Game.journeyEnding.hidden));
  for(const rotated of [false,true]){const tc=await context.browser().newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),tp=await tc.newPage();try{tp.on('pageerror',e=>errors.push(String(e)));await tp.goto(url);await tp.waitForFunction(()=>Game.state==='menu',null,{timeout:65000});await tp.evaluate(rotated=>{Game.forcedLandscape=rotated;Game.resizeCanvas();Game.beginTreasureExtraction();Game.state='playing';Game.player.invuln=999;Game.updateExtraction(480.1);const s=Game.extraction.sites[0];for(const e of Game.enemies.filter(e=>e.extractionGuardId===0))e.takeDamage(99999,false,0,s.x,s.y);Game.updateExtraction(.01);Game.player.x=s.x;Game.player.y=s.y;Game.collectExtractionShard(0);Game.player.x=Game.extraction.exit.x;Game.player.y=Game.extraction.exit.y;Game.openExtractionChoice();},rotated);const r=await tp.evaluate(()=>Game.getExtractionChoiceLayout().leave),q=await tp.evaluate(r=>{const b=Game.canvas.getBoundingClientRect(),x=r.x+r.w/2,y=r.y+r.h/2;return Game._rotate90?{x:b.x+(1-y/540)*b.width,y:b.y+x/960*b.height}:{x:b.x+x/960*b.width,y:b.y+y/540*b.height};},r);await tp.touchscreen.tap(q.x,q.y);await tp.waitForFunction(()=>Game.extraction.channeling);check(`Native extraction touch ${rotated?'rotated':'portrait'} starts one channel`,await tp.evaluate(()=>!Input.joystick.active&&Game.extraction.channel<1));}finally{await tc.close();}}
  check('No v0.25 runtime errors',errors.length===0);return {passed:true,checks,errors,screenshots};
 }catch(e){await shot('failure');return {passed:false,failure:String(e),checks,errors,screenshots,snapshot:await p.evaluate(()=>({state:Game.state,theme:Game.levelData?.theme,extraction:Game.extraction,ending:Game.journeyEnding,pending:Game.journeyEndingPending}))};}finally{await context.close();}
}
